### ISSUE TITLE
how to disable toolbar buttons on HTML code view mode

### ISSUE THREAD

**Issue by sshabdali** [kolkov/angular-editor#1]
Thanks for sharing this simple WYSIWYG editor, work perfectly for me in angular 6.

I have done following to customize it slightly, so i thought lets share it with others.

<angular-editor formControlName="content" [config]="config" (viewMode)="modeChange($event)"></angular-editor>

modeChange(event) {
   this.config.placeholder = event ?  'Enter text here...' : 'Copy html markup here...';
}

Is it possible to disable the other toolbar buttons on HTML code view mode?

**Comment by kolkov** [comment]
Hi! Thank you for your interest in the project!
This feature is not implemented yet. You want to disable buttons or hide all panels in the HTML mode?

**Comment by sshabdali** [comment]
Disabling buttons in html mode would be a good option.
It would also be good if i can set the default font via AngularEditorConfig

Thanks

**Comment by kolkov** [comment]
Try new version please with disabling buttons in HTML mode.
https://angular-editor-wysiwyg.stackblitz.io/

**Comment by Kang-Huang** [comment]
hi Andrey Kolkov,
I am very interested in your project. I tried it and it worked very well.
Will you add image file upload to you project?
Cheers,
Yongtai

**Comment by kolkov** [comment]
Thanks! Yes, it's in the plans for the next releases.

**Comment by kolkov** [comment]
Latest release provide functionality for default font setting via `defaultFontName`
Please check this!

**Comment by sshabdali** [comment]
Yep all looks good 👍, It fulfills my project requirement for now.
Looking forward for more features in up coming releases. 

Thanks

**Comment by KhaMinhVLU-2017** [comment]
You can icon HTML Code at file kolkov-angular-editor.js 
The code below: 
  <button [id]=\"'toggleEditorMode-'+id\" type=\"button\" title=\"HTML Code\" class=\"angular-editor-button\"\n            (click)=\"triggerCommand('toggleEditorMode')\" tabindex=\"-1\"><i class='fa fa-code'></i></button>\n 

![image](https://user-images.githubusercontent.com/31025072/64347717-993cb680-d01e-11e9-9e05-daeca0543ad2.png)
