### ISSUE TITLE
Define custom styles

### ISSUE THREAD

**Issue by danail-vasilev** [kolkov/angular-editor#10]
Hi,
Is it possible to define custom styles via the toolbar dropdown ?
Regards,

**Comment by kolkov** [comment]
Do you want to declare new styles in the editor or in the application?

**Comment by kolkov** [comment]
@melhaer If I understand you correctly, you need a setting that can be made when the editor is initialized? or on the end-user side?

**Comment by danail-vasilev** [comment]
Hello @kolkov , thank  you for you reply!
Me and my friend are looking for the apply css class functionality - [demo](https://demos.telerik.com/aspnet-ajax/editor/examples/overview/defaultcs.aspx) and [article](https://docs.telerik.com/devtools/aspnet-ajax/controls/editor/functionality/toolbars/dropdowns/css-styles).
Thank you !

**Comment by kolkov** [comment]
@danail-vasilev Who will set this custom formatting? The end user through the editor's menu or programmer when setting up the editor?

**Comment by danail-vasilev** [comment]
The programmer will define the set of custom styling, so the end user can apply the desired one.

**Comment by kolkov** [comment]
Hi! I initialized support for custom classes. Try it please.
If it usefull, we will extend later.

**Comment by danail-vasilev** [comment]
Hi,
Thank you very much for the immediate implementation !
I think the read.me should be updated with the proper config property:
customClasses: [ // optional
should be renamed to customStyles as per this line:
https://github.com/kolkov/angular-editor/commit/6d09b4542647827f467ac9897369823d619817c9#diff-847dab7018900297203b3ea812a02a36R56
Regards,

**Comment by danail-vasilev** [comment]
I have also another questions regarding predefined styles. What is the purpose of Default and Normal options because they don't take effect on selection ?

**Comment by mohdaftab93** [comment]
Hello,
I want only a few options on the editor. Like only basic text styling.
Is it possible to remove other options from the editor?

**Comment by Aleksluciano** [comment]
> Hello,
> I want only a few options on the editor. Like only basic text styling.
> Is it possible to remove other options from the editor?

I am doing this way and is working:

In html file put any id to the component editor, for example "myEditor"  
<angular-editor id="myEditor" </angular-editor>

In Css file put the code below:

:host /deep/ angular-editor#myEditor .angular-editor-button[title="Insert Image"]{
  display: none
  }

If you want remove others buttons, just copy and paste the code and change the title.

**Comment by updatepromise2020** [comment]
hi @kolkov  i saw you latest release to add @kolkov/angular-editor to angular 6 + . My question is i wanna add a new custom button at the end of this toolbar in angular , is it possible?if yes, can you please paste the code here?

**Comment by kolkov** [comment]
@updatepromise2020 Hi! This is not realized yet. 
Please open separate issue for this feature request.

**Comment by AdityaSrivastava21** [comment]
I want to add some custom features (dropdown) inside angular-editor-toolbar. Is it possible?

**Comment by IslamElKassas** [comment]
Hi @kolkov , your editor is perfect, just ask please if you can implement a tables class, its is very useful and realy needed. Thank you

**Comment by AshuT930** [comment]
Hi @kolkov, **How can I remove certain options from the heading dropdown?** I want to remove Predefined and standard options from the dropdown. Not sure how to achieve that in Kolkov editor.

**Comment by ajeetkumarver** [comment]
Hii @kolkov , I chosen the justifyRight and then added some text and trying to send via mail , but In mail body I got only this -- <div><span>text added.....</span></div> as  HTML code , it does't have any text styling in it ..... so how Can I add this?

**Comment by ajeetkumarver** [comment]
Hii @kolkov , also how can I add custom styling to that custom classes like richText?
