### ISSUE TITLE
Text area needs a tabindex

### ISSUE THREAD

**Issue by Gaugeforever** [kolkov/angular-editor#102]
The text area on the control doesn't have a tabindex.  Setting tabindex attribute to 0 should allow the control the be tabable regardless of where it is placed on a page.  Currently, not having one set makes focusing this control programmatically very difficult (and hacky).  The angular way of doing this does not recognize it as a valid focusable control because it is missing a tabindex.

See [https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex](tabindex)

**Comment by kolkov** [comment]
Hello! What solution do you offer? To allow index assignment in `<angular-editor>` tag element?

**Comment by Gaugeforever** [comment]
Adding tabindex="0" to the tag that contains the text area.
`<textarea tabindex="0">`
for example.

For now we can target it with tabbing, but we cannot target the textarea programmatically to be focused.  Our need is that we open an overlay with this control on it, and we want to focus this control on that overlay so the user can start typing right away.  So really any way to target this control's text area to focus it.

I hope this makes sense.
