### ISSUE TITLE
Disable selected toolbar buttons

### ISSUE THREAD

**Issue by ZuzanaKurillova** [kolkov/angular-editor#103]
Hi Andrey, thank you very much for a very helpful project. I am using it on my site but I would like to disable two buttons, specifically image upload (we have a different tool for that) and html view mode button (not needed for our purpose). Is there any way how to do so in the configuration of the component? 
Thank you
Zuzana Kurillova

**Comment by kolkov** [comment]
Hi! Thanks!
Only by css now...(

**Comment by ZuzanaKurillova** [comment]
Thank you, I didn't make it by css, as the component wasn't reacting on the class names in it. I have used another approach, downloaded your library and used it as part of the project. I removed all the buttons I didn't need. Everything is working perfectly but one button: bold. For some reason it is only adding <b></b> but on next click it doesn't remove it. Do you please have a clue why? I have problems understanding the process of command emitting somehow. Thanks!
Zuzana

**Comment by ZuzanaKurillova** [comment]
I mean adding tags <b></b> but not removing them on next click. Thanks.

**Comment by kolkov** [comment]
https://angular-editor.kolkov.ru/ demo works as expected.

**Comment by ZuzanaKurillova** [comment]
Could you please suggest how to remove the button for image upload by CSS when I use it as a component being installed to my project? Thanks
Zuzana

**Comment by kolkov** [comment]
This may help
https://github.com/kolkov/angular-editor/issues/19
https://github.com/kolkov/angular-editor/issues/11
or remove `@import "style";` and redefine that you need in you project...
https://github.com/kolkov/angular-editor/blob/master/projects/angular-editor/src/lib/angular-editor-toolbar.component.scss#L1

**Comment by ZuzanaKurillova** [comment]
Thank you.
