### ISSUE TITLE
TypeError: Cannot read property 'nativeElement' of undefined

### ISSUE THREAD

**Issue by Aadithan** [kolkov/angular-editor#115]
I am getting the below error when i define ngModel
**<angular-editor [placeholder]="'Enter text here...'" id="editor1"  [config]="editorConfig" [(ngModel)]="htmlContent"  ></angular-editor>**

core.js:7187 ERROR TypeError: Cannot read property 'nativeElement' of undefined
    at AngularEditorComponent.togglePlaceholder (kolkov-angular-editor.js:1422)
    at AngularEditorComponent.writeValue (kolkov-angular-editor.js:1395)

**Comment by kolkov** [comment]
@Aadithan Hi! Thanks, provide your version of Angular please.

**Comment by Aadithan** [comment]
@kolkov Thanks for your reply.

@angular/cli": "~8.0.6
@angular/compiler": "~8.0.3"
@angular/compiler-cli": "~8.0.3

Here is my full source code 

https://github.com/Aadithan/MyBlog/tree/master/MyBlogUI

**Comment by kolkov** [comment]
@Aadithan I don't see this error https://kolkov.ru/editpost

**Comment by kolkov** [comment]
ng version
```
D:\test\my_blog>ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.1.1
Node: 12.6.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.801.1
@angular-devkit/core         8.1.1
@angular-devkit/schematics   8.1.1
@schematics/angular          8.1.1
@schematics/update           0.801.1
rxjs                         6.4.0


```

**Comment by Aadithan** [comment]
@kolkov Sorry i didnt mention this clearly in my first post. When I add [(ngModel)]="htmlContent" to display my Htmloutput by two binding i am getting that error.

<angular-editor [placeholder]="'Enter text here...'" id="editor1"  [config]="editorConfig" [(ngModel)]="htmlContent"></angular-editor>

I have updated the source code on the same path.

https://github.com/Aadithan/MyBlog/tree/master/MyBlogUI

Thanks

**Comment by kolkov** [comment]
@Aadithan I see, you using Ivy compiler option to build your app.
Ivy in early beta now, and not ready for production, only for testing purpose.

**Comment by egeozbek** [comment]
@kolkov Hi. I am having the same issue using reactive forms. nativeElement of undefined not found error. I have moved my placeholder from html to config object but problem still persists.

**Comment by egeozbek** [comment]
@kolkov As additional info ,problem started to appear after I upgraded to angular 8. After the upgrade, @ViewChild directive started to give off error, such that it must have a second argument, which I made as {static : false} (following instructions on stackoverflow).

**Comment by kolkov** [comment]
> As additional info ,problem started to appear after I upgraded to angular 8. After the upgrade, @ViewChild directive started to give off error, such that it must have a second argument, which I made as {static : false} (following instructions on stackoverflow).

where did you do this in the compiled library?
