### ISSUE TITLE
How to use angular editor for editing text?

### ISSUE THREAD

**Issue by ssubara** [kolkov/angular-editor#116]
Dear, Mr Kolkov,
How I can setup value data in angular-editor? I want to change existing text, and I can't find way how to put existing text inside editor. Thanks

**Comment by kolkov** [comment]
Hi! Simply populate model for existing text content like in ordinary form field.

**Comment by kolkov** [comment]
![Screenshot_20190722-213926_Chrome](https://user-images.githubusercontent.com/3740898/61656528-a2b9cb80-acc9-11e9-8a12-50e9e4e5537f.jpg)

**Comment by ssubara** [comment]
Thanks a lot! Now I see. :( Sorry
