### ISSUE TITLE
Alignment does not work properly

### ISSUE THREAD

**Issue by GApaniagua** [kolkov/angular-editor#117]
The alignment of the text is not saved in the html outpu, that is to say if I save it I place it in the center this will not go into the resulting value.

![image](https://user-images.githubusercontent.com/35755167/62141467-da1c0f80-b2a9-11e9-8e3b-046096f7d79d.png)

**Comment by DanielFrugoni** [comment]
Have the same prob. How can I fix it ? (Center and Right) is not working for me
Thx !!

**Comment by renatohr** [comment]
Has someone fixed this issue?

**Comment by renatohr** [comment]
I've found out that if you set the sanitize property in editorConfig to false, then it will not strip text-alignment from style:

editorConfig: AngularEditorConfig = {
  ...
    sanitize: false, -----> SET THIS TO FALSE
};

**Comment by renatohr** [comment]
And then you can use a "noSanitize" pipe (https://stackoverflow.com/questions/47681813/angular-2-sanitizing-html-stripped-some-content-on-css-style?rq=1) to show your HTML properly, bypassing the sanitizer from Angular:

![image](https://user-images.githubusercontent.com/42399028/68446120-998e3500-01ba-11ea-857f-86e16f169ba6.png)

**Comment by RabbitYui** [comment]
I've got the problem with alignment too. It doesn't work in Google Chrome
Can somebody help me? 

Thank you!

**Comment by renatohr** [comment]
> I've got the problem with alignment too. It doesn't work in Google Chrome
> Can somebody help me?
> 
> Thank you!

@RabbitYui Have you tried my solution above?

**Comment by RabbitYui** [comment]
> > I've got the problem with alignment too. It doesn't work in Google Chrome
> > Can somebody help me?
> > Thank you!
> 
> @RabbitYui Have you tried my solution above?

Yes, it's help a little, but he problem was that my text wasn't sanitized before showing on page.
Adding bypassSecurityTrustHtml() solved the problem
