### ISSUE TITLE
disable focus by default?

### ISSUE THREAD

**Issue by shawngrona** [kolkov/angular-editor#120]
is there some way to disable the focus by default?  its a little weird if the editor is part of a larger form when the auto focus is this angular-editor.  thank you for info, thank you kolkov for the tool!

**Comment by kolkov** [comment]
@shawngrona Try new version please. now nou can set the properti for autofocus. Thanks for the report.

**Comment by siva-pydakula** [comment]
I am using angular 6 and  according to my company policy I can't update angular version please suggest me how to do the same thing in the Angular6

**Comment by siva-pydakula** [comment]
@kolkov can you please let me know about this issue

**Comment by siva-pydakula** [comment]
@kolkov  can you please reply for this issue
