### ISSUE TITLE
Clear Class is not working in custom class menu

### ISSUE THREAD

**Issue by akvaliya** [kolkov/angular-editor#121]
When we apply any class then it is impossible to remove it.

It has clear class option but it's doing nothing.

![angular-editor](https://user-images.githubusercontent.com/25152577/62290154-40f22200-b47e-11e9-994a-d2c8c5c0b792.png)

What am i missing here?

**Comment by kolkov** [comment]
Thanks! This is not implementet yet. (

**Comment by fahimehahmadi94** [comment]
Is this still a problem?

**Comment by ashishakm** [comment]
How to rename “clear class” to “Remove style”
