### ISSUE TITLE
Bug with onDestroy

### ISSUE THREAD

**Issue by SergeyVelich** [kolkov/angular-editor#123]
I have component only with editor. If I go route - all is good, I can edit my html.
If I want go to ref (to another route in this app) I have error:

ERROR Error: Uncaught (in promise): TypeError: this.blurInstance is not a function
TypeError: this.blurInstance is not a function
    at AngularEditorComponent.ngOnDestroy (kolkov-angular-editor.js:1110)
    at callProviderLifecycles (core.js:28212)
    at callElementProvidersLifecycles (core.js:28171)
    at callLifecycleHooksChildrenFirst (core.js:28153)
    at destroyView (core.js:38603)
    at callViewAction (core.js:38762)
    at execComponentViewsAction (core.js:38670)
    at destroyView (core.js:38602)
    at callWithDebugContext (core.js:39716)
    at Object.debugDestroyView [as destroyView] (core.js:39313)
    at resolvePromise (zone-evergreen.js:797)
    at resolvePromise (zone-evergreen.js:754)
    at zone-evergreen.js:858
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:34182)
    at ZoneDelegate.invokeTask (zone-evergreen.js:390)
    at Zone.runTask (zone-evergreen.js:168)
    at drainMicroTaskQueue (zone-evergreen.js:559)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:469)
    at invokeTask (zone-evergreen.js:1603)
defaultErrorLogger @ core.js:9110

**Comment by kolkov** [comment]
Hi! Provide your versions please.

**Comment by pbut** [comment]
H! kolkov,

I have this problem too. I use angular-editor latest version. My development is:

Angular CLI: 8.2.0
Node: 10.16.1
OS: win32 x64
Angular: 8.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.0
@angular-devkit/build-angular     0.802.0
@angular-devkit/build-optimizer   0.802.0
@angular-devkit/build-webpack     0.802.0
@angular-devkit/core              8.2.0
@angular-devkit/schematics        8.2.0
@angular/cdk                      8.1.2
@angular/fire                     5.2.1
@ngtools/webpack                  8.2.0
@schematics/angular               8.2.0
@schematics/update                0.802.0
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.38.0

Regards,

**Comment by sureeraya** [comment]
I got same error. 

>  this.blurInstance is not a function TypeError: "this.blurInstance is not a function"

I use angular-editor latest version with angular 8.
-----------------------------------------------------------
@angular-devkit/architect         0.802.0
@angular-devkit/build-angular     0.802.0
@angular-devkit/build-optimizer   0.802.0
@angular-devkit/build-webpack     0.802.0
@angular-devkit/core              8.2.0
@angular-devkit/schematics        8.2.0
@angular/cdk                      8.1.2
@angular/fire                     5.2.1
@ngtools/webpack                  8.2.0
@schematics/angular               8.2.0
@schematics/update                0.802.0
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.38.0

**Comment by kolkov** [comment]
Thanks! Confirmed. If we didn't switch to the source code mode, listeners was not connected, but we tried to unsubscribe.

**Comment by sureeraya** [comment]
Temporary I comment these 2 lines in angular-editor.component.js It's work but don't know is correct or not. Just information. ^^

    /** 
     * @return {?}
     */
    ngOnDestroy() {
        // this.blurInstance();
        // this.focusInstance();
    }

**Comment by sureeraya** [comment]
Thank you very much. ^^

**Comment by SergeyVelich** [comment]
Thank you) It's working now
