### ISSUE TITLE
Editor Service

### ISSUE THREAD

**Issue by FranciscoPQuiros** [kolkov/angular-editor#125]
In function 'executeInNextQueueIteration' from angular-editor.service.d.ts to trigger error when install and compile the project. I suppose that '...args' should be between 
square bracket. Can you give me feedback?

**Comment by kolkov** [comment]
Hi! What version of Angular you are using?

**Comment by FranciscoPQuiros** [comment]
I am using 6.2.9 Angular version. The issue is for that?
