### ISSUE TITLE
Inline style capture

### ISSUE THREAD

**Issue by pallavi1993** [kolkov/angular-editor#132]
HI, 
Am able to select the html content but how can i capture html content along with its styling?

For example i align a heading to center but it captures as heading tag only and does not reads the center aligning style.

**Comment by renatohr** [comment]
Same problem here. The ngModel does not capture text-align property

**Comment by renatohr** [comment]
I've found out that if you set the sanitize property in editorConfig to false, then it will not strip text-alignment from style:

editorConfig: AngularEditorConfig = {
  ...
    sanitize: false, -----> SET THIS TO FALSE
};

**Comment by renatohr** [comment]
And then you can use a "noSanitize" pipe (https://stackoverflow.com/questions/47681813/angular-2-sanitizing-html-stripped-some-content-on-css-style?rq=1) to show your HTML properly, bypassing the sanitizer from Angular:

![image](https://user-images.githubusercontent.com/42399028/68446120-998e3500-01ba-11ea-857f-86e16f169ba6.png)
