### ISSUE TITLE
Ksrvnn03

### ISSUE THREAD

**Issue by ksrvnn03** [kolkov/angular-editor#134]
How to disable copy and paste in editor, and html contents.

**Comment by kolkov** [comment]
Hi! Why you need to disable copy and paste?
At moment this works only when editor is disabled.

**Comment by ksrvnn03** [comment]
If user  copy and paste html code also saved in database, i need only type mode option. any config option available ?

**Comment by kolkov** [comment]
No, this functionality is not implemented yet.

**Comment by ksrvnn03** [comment]
Ok. Thanks.

**Comment by kolkov** [comment]
Since this is the standard input field try to use this standard way.
https://stackoverflow.com/questions/12805803/disable-copy-paste-in-html-input-fields

**Comment by ksrvnn03** [comment]
Its work disable(copy paste) in editor. Thanks Andrey Kolkov.
