### ISSUE TITLE
Need public accesor for Angular 6 version at insertHtml function

### ISSUE THREAD

**Issue by gwillebaldhub** [kolkov/angular-editor#135]
Hi, please, could you remove the private accesors of insertHtml functions at angular-editor.service for at least one older version 1.5.x because newer versions does not compile using Angular 6, our project is pretty big, and is impossible for us update to ng7 yet, so would be fantastic if you could remove that restriction from some of the old versions!!
Thanks for your time, your library is awesome :D

**Comment by kolkov** [comment]
Maybe you just copy the library into your project until you upgrade to the new version of Angular?

**Comment by kolkov** [comment]
Or you can try to use npm link...

**Comment by gwillebaldhub** [comment]
> Maybe you just copy the library into your project until you upgrade to the new version of Angular?

Yes, I was thinking the same, including the library, Editing it and use it until a future update of our project.
