### ISSUE TITLE
Font color changing when apply bold

### ISSUE THREAD

**Issue by Matias316** [kolkov/angular-editor#137]
Hi, when I apply bold to a text the font color is changed to yellow:

![image](https://user-images.githubusercontent.com/40250041/63275572-25598a80-c278-11e9-9cbd-38465702e86a.png)

![image](https://user-images.githubusercontent.com/40250041/63275654-4b7f2a80-c278-11e9-8c75-51d88d1866ef.png)

The workaround is to just select the text and change the font color, but I was wondering if this is well-known issue..

Thanks

**Comment by kolkov** [comment]
Hi! Look at the styles of your site, maybe they overlap the style of bold text.

**Comment by Matias316** [comment]
Hi Kolkov, yes, you were right, the problem was with a definition in the styles of my site :). Thank you for your help!
