### ISSUE TITLE
JHipster / Angular 8 compliant?

### ISSUE THREAD

**Issue by mheidt** [kolkov/angular-editor#139]
Hello,

I tried to integrate your example into a angular 8 based jhipster project.

Either way:
outside the form this one:
<angular-editor [(ngModel)]="htmlContent" [config]="editorConfig"></angular-editor>

or inside:
<angular-editor formControlName="htmlContent" [config]="editorConfig"></angular-editor>

Having both in the controller:
export class .....Component implements OnInit {
htmlContent: '';

and

 editForm = this.fb.group({
    id: [],
    body: [null, [Validators.required]],
    htmlContent: [],

fails with the following error: (js console)
No value accessor for form control with name: 'htmlContent'
 at _throwError (forms.js?8087:2265)
    at setUpControl (forms.js?8087:2175)
    at FormGroupDirective.addControl (forms.js?8087:5383)
    at FormControlName._setUpControl (forms.js?8087:5984)
    at FormControlName.ngOnChanges (forms.js?8087:5905)

Did I miss anything?

Kind regards,
Markus

**Comment by kolkov** [comment]
https://stackblitz.com/edit/angular-editor-wysiwyg this example is for Angular 8.

**Comment by mheidt** [comment]
Thanks, I took the parent module.ts of the module.ts that is supposed to have the changes.
