### ISSUE TITLE
Clear Custom Styles using normal Clear Formatting (X) button

### ISSUE THREAD

**Issue by melhaer** [kolkov/angular-editor#14]
Hello,

When I have custom styles set, I would like to select a specific part of the text, and using the Clear Formatting button, to remove the element with the specific CSS class.

Now, when I am using Custom Classes, and set a specific style, and I want to remove it, it is almost impossible, and the only option is to remove the text completely and start from the beginning.

And I would like to know what the option  - **Clear Class** - does (Check image attached). I was expecting to remove any picked CSS class, but it does nothing? Or Am I wrong?

![clear-class](https://user-images.githubusercontent.com/16577124/43191133-37381300-9003-11e8-88bf-7ee008142100.jpg)

Anyway, I think it would be more clear and UX proper the classes and all formatting to be cleared using the Clear Formatting button.

Thanks for you wonderful control and dedication to it!

**Comment by kolkov** [comment]
Hi! This is not implemented yet!

**Comment by kolkov** [comment]
Try formatting default to clear styles.

**Comment by kolkov** [comment]
closed by https://github.com/kolkov/angular-editor/commit/bb9454ae38f125429beac546470ad248ebdbf06a
