### ISSUE TITLE
Justify / Indent to html

### ISSUE THREAD

**Issue by mheidt** [kolkov/angular-editor#140]
Hello,

You created a really nice piece of code here.
After a little playing I was wondering, if it is possible to deactivate single groups.
Like no uploads, no indent, no justification or the like.

Especially since indent, justification and background color is not generated into the resulting html.
Is this a bug?

Kind regards,
Markus

**Comment by kolkov** [comment]
Hi! Try to view source html code to check this.

**Comment by mheidt** [comment]
I bound it to  a variable and stored it into the database. 
I don't see the html code of those formats.
Picture upload, font, font color, b, i etc are fine.

**Comment by mheidt** [comment]
But more important would be the feature request that let us disable certain actions.

**Comment by mheidt** [comment]
Ok, I saw the div style. But the angular component can't handle it. And Swing UI can't handle pictures and videos f.e.
That's why I would need the mentioned feature

**Comment by kolkov** [comment]
Disable buttons implemented in latest version.
