### ISSUE TITLE
Text box resizing button has disappeared

### ISSUE THREAD

**Issue by alissonmbc** [kolkov/angular-editor#147]
The diagonal lines used to resize the text box have disappeared in recent updates, is there a way to work around this and get the option back?

**Comment by kolkov** [comment]
Hi! What do you mean by diagonal lines?

**Comment by alissonmbc** [comment]
sorry for not specifying, I was referring to those:

![image](https://user-images.githubusercontent.com/32646589/64431527-02f5a880-d091-11e9-99b0-51eb57d09c78.png)

**Comment by renatolm** [comment]
Kolkov, you are the best!
Thnx for the good work.
