### ISSUE TITLE
conflict with last version font awesome and angular-editor

### ISSUE THREAD

**Issue by mahdiyee** [kolkov/angular-editor#148]
I used last version of font awesome an used it in my project,
when I go to page with angular-editor, last version font awesome doesnt work and first version work ! just in this page ! 
do u have any solution ?

**Comment by kolkov** [comment]
H! In general, I see no reason that two fonts would not work at the same time. It is very strange.

**Comment by kolkov** [comment]
But in general I want to use own icons font or svg font.
