### ISSUE TITLE
Text background color not added to HTML Output  

### ISSUE THREAD

**Issue by swapnika436** [kolkov/angular-editor#151]
Changed the text background color. 
But there is not difference is html output. 

How can we capture the background color?
![image](https://user-images.githubusercontent.com/25026390/64938121-6db99780-d87a-11e9-9cff-eec5bcb69309.png)

**Comment by kolkov** [comment]
Hi! I think that standart dome sanitizer strippes this for some attributes.

![image](https://user-images.githubusercontent.com/3740898/64941045-4b218180-d86e-11e9-9767-c851fc8d9545.png)

**Comment by swapnika436** [comment]
Hi,
Thank you for your response.
Its working.

**Comment by saratSubramaniam** [comment]
@swapnika436 - Could you please tell me how to apply this fix ?

**Comment by Mounica1995** [comment]
How it works??

**Comment by bsharp-azhar** [comment]
how does it work? not working for me

**Comment by deepmirchandani** [comment]
@bsharp-azhar in config by setting **sanitize: false**, it started working.
