### ISSUE TITLE
Problem with version 0.15.x

### ISSUE THREAD

**Issue by BkMiguel12** [kolkov/angular-editor#152]
Good morning !

I am using Angular 6 and AngularEditor 0.15.x (this is what the documentation says).

However, I always get the same error:

![imagen](https://user-images.githubusercontent.com/21348563/65059424-fcdeb200-d943-11e9-9d78-5f9f280be8b6.png)

**Comment by kolkov** [comment]
Thanks! This fixed in next versions... but I try to backport this fix.

**Comment by BkMiguel12** [comment]
Can I use 0.14 and Angular 6?
That version works fine?

**Comment by kolkov** [comment]
This problem will disappear, but there are other problems...

**Comment by BkMiguel12** [comment]
Sorry for bothering you so much, but what kind of problems?

**Comment by kolkov** [comment]
The inability to use 2 editors at the same time; font installation by default does not work and some more.

**Comment by BkMiguel12** [comment]
Well I don't need two editors at the same time. 
The problem that I have encountered so far in that version is the icons ... only the Font icon appears (fa fa-font)

**Comment by kolkov** [comment]
Where appears?

**Comment by kolkov** [comment]
Try version 0.15.5 please.
