### ISSUE TITLE
Unordered list not working

### ISSUE THREAD

**Issue by deepalishinde247** [kolkov/angular-editor#153]
I am implementing this editor in angular 7 and I installed kolkov/angular-editor of version 0.18.4. But Unordered list not working there. Please give me solution

**Comment by kolkov** [comment]
Hi! Do you see any errors in the browser console?

**Comment by deepalishinde247** [comment]
No..there is no errors on console but there is warning that 'sanitizing HTML stripped some content, see http://g.co/ng/security#xss'
![warning](https://user-images.githubusercontent.com/53968015/65369550-34af6780-dc6c-11e9-8b9b-56d028a534dc.jpg)

**Comment by kolkov** [comment]
Thanks! Try to turn off standard DOM sanitizer please.

**Comment by deepalishinde247** [comment]
Ho to turn off standard DOM sanitizer?

**Comment by kolkov** [comment]
https://github.com/kolkov/angular-editor/blob/2ee0226a2bf2c2efe5f84f5873db8183f2985781/projects/angular-editor-app/src/app/app.component.ts#L25

**Comment by deepalishinde247** [comment]
Yeah..I did that..But it not worked. Now warning is removed from console but still unordered list not working.

**Comment by kolkov** [comment]
Provide working example at stackblitz with this bugs please.

**Comment by JohanurRahman** [comment]
Not working for me either. Working on v0.18.7... In my case there isn't any error or warning in the console

**Comment by kolkov** [comment]
Hi! Do you use dom sanitizer at config?

**Comment by JohanurRahman** [comment]
This is my config 

https://gist.github.com/JohanurRahman/0256bbe01bd76f617ee5988ecdb7efa7

**Comment by kolkov** [comment]
Thanks! Provide minimal working example with reprezentation for this bug please.
