### ISSUE TITLE
Possible bug...

### ISSUE THREAD

**Issue by thecherrytree** [kolkov/angular-editor#155]
Hey @Kolkov,

This one might actually be a bug. Everything works fine, except when I go to edit my form, the form does the following strange defaults with the drop downs (and I cannot close them).

![image](https://user-images.githubusercontent.com/9562351/65339838-e67e6380-db9a-11e9-8fc6-a1e19968dffa.png)

There are no errors...

Version of Angular Editor:
```
Angular: 8.2.2
1.0.0-beta3
1.0.0-beta 4
```

Perhaps this is an issue with CSS stylings somewhere at a global level? My config is pretty minimal on the editor:
```
  config: AngularEditorConfig = {
    editable: true,
    spellcheck: true,
    translate: 'no'
  };
```

**Comment by thecherrytree** [comment]
This appears to be the issue:
![image](https://user-images.githubusercontent.com/9562351/65340504-5d682c00-db9c-11e9-86dc-a4ae4b3b6c27.png)

If you notice the `display:none` is not taking. When I override it with `!important`, those drop downs close.

**Comment by kolkov** [comment]
Hi! Provide an example on stackblitz please.

**Comment by kolkov** [comment]
https://angular-editor.kolkov.ru/ this works as expected.

**Comment by thecherrytree** [comment]
@kolkov - the issue is with css stylings that overrode display stylings in mat-card-dialog. 

If anyone is leveraging something like this:

```
::ng-deep mat-dialog-container span {
    display: inline-block !important;
}
```

Then the spans that contain the headings for the editor will default to inline as well (thus keeping them open). I was able to create a satisfactory workaround.
