### ISSUE TITLE
Image upload is broken

### ISSUE THREAD

**Issue by MurrayFurtado** [kolkov/angular-editor#156]
I am using latest version (beta.4) with angular 8.22 and I have tried with betas 0, 1, 2 and the feature always throws an exception after uploading the image.

`core.js:4002 ERROR TypeError: Cannot read property 'nativeElement' of undefined
    at AngularEditorToolbarComponent.push../node_modules/@kolkov/angular-editor/fesm5/kolkov-angular-editor.js.AngularEditorToolbarComponent.fileReset (kolkov-angular-editor.js:1091)`

It susequently doesn't display them.

My upload returns a json with a valid imageUrl property. Can anyone help?

**Comment by kolkov** [comment]
Hi! Provide an example of this issue on stackblitz please.
