### ISSUE TITLE
Duplicated Heading 7 in SelectOptions array for headings 

### ISSUE THREAD

**Issue by Ashiv3r** [kolkov/angular-editor#158]
Hey!

We've found that you duplicated h7 heading inside SelectOptions array for headings, which results in double display inside select.

https://github.com/kolkov/angular-editor/blob/2ee0226a2bf2c2efe5f84f5873db8183f2985781/projects/angular-editor/src/lib/angular-editor-toolbar.component.ts#L23

Cheers!

**Comment by kolkov** [comment]
Thanks!
