### ISSUE TITLE
Editor not working with angular Validators 

### ISSUE THREAD

**Issue by cpratiksha** [kolkov/angular-editor#160]
Not supporting 
  `generateForm() {
    this.dataManagementModalForm = this.fb.group({
   descriptionData: [null, [Validators.required, CustomValidator.maxLengthValidators(255),CustomValidator.notBlank]],
 });`

**Comment by cpratiksha** [comment]
Need help on this editor not supporting this validator not Blank

**Comment by kolkov** [comment]
What does this validator do?

**Comment by cpratiksha** [comment]
This is my validator.ts file 
I want to use it in an angular way -it restricts a user to type only empty spaces and disabling my submit button.
Editor not supporting standard angular validation process.
 https://angular.io/api/forms/Validators
`
import { AbstractControl, ValidatorFn } from '@angular/forms';

export class CustomValidator {
  
  static maxLengthValidators(limit): any {
    return (c: AbstractControl): { [key: string]: boolean } | null => {

        if (c.value && (c.value.length>limit)) {
            return { maxLengthError: true };
        }
        return null;
    };
  }

  static notBlank(string): any {
    if (string.pristine) {
        return null;
    }
    if (string.value && string.value.trim().length > 0) {
        return null;
    }
    return {
      emptyStringError : true
    };
  }

}
`

**Comment by cpratiksha** [comment]
Hi , did you find something on it.

**Comment by kolkov** [comment]
Create minimal example with representation of this 'bug' please! Thanks!
