### ISSUE TITLE
Angular 8, build --prod fails?

### ISSUE THREAD

**Issue by vicatcu** [kolkov/angular-editor#161]
My project builds fine without the `--prod` flag, but fails to build with the `--prod` flag with several errors like the following:

```
ERROR in ./node_modules/angular-editor/kolkov-angular-editor.ngfactory.js
Module not found: Error: Can't resolve '@kolkov/angular-editor' in '/my-project/node_modules/angular-editor'
```

**Comment by kolkov** [comment]
What versions you are using?

**Comment by vicatcu** [comment]
```
Angular:

   @angular-devkit/build-angular : 0.803.6
   @angular-devkit/schematics    : 8.3.6
   @angular/cli                  : 8.3.6

System:

   NodeJS            : v10.16.0 (/home/vic/.nvm/versions/node/v10.16.0/bin/node)
   npm               : 6.12.0
   OS                : Linux 4.15
```

**Comment by vicatcu** [comment]
I'm going to close this as a false alarm because I think it was just how I was listing my fork as a dependency and importing it in my typescript files. I was leaving off the "@kolkov/" on both counts and apparently build --prod doesn't like that for some reason.
