### ISSUE TITLE
Undo redo not working while adding content programatically

### ISSUE THREAD

**Issue by rajkotgire** [kolkov/angular-editor#165]
Hi Andrey Kolkov, 
I am trying to update ngmodel  through js something similar as mentioned in below stackblitz link
[https://stackblitz.com/edit/angular-editor-wysiwyg-gscvmh?file=src/app/app.component.ts]() 
Please click on Click to add #Dummy Text# to see the changes.
however model gets updated but i am not able to perform Undo and redo operation.
Can you please guide me to right direction.

**Comment by kolkov** [comment]
undo and redo use browser implementations.  if the browser does not see the changes, then they will not work.

**Comment by kolkov** [comment]
https://stackoverflow.com/questions/11579255/undo-and-redo-in-wysywyg-contenteditable-in-swt-doesnt-work

**Comment by rajkotgire** [comment]
> https://stackoverflow.com/questions/11579255/undo-and-redo-in-wysywyg-contenteditable-in-swt-doesnt-work

**Comment by rajkotgire** [comment]
> undo and redo use browser implementations. if the browser does not see the changes, then they will not work.

Ok, this is means, content added programatically are aren't visible to browser and so undo redo wont work, and if we still want to implement similar need to write our own code to to make this work, rt

**Comment by RaquelJusticia** [comment]
I really like this package, it is very clear and useful.
What if adding [disabled]="htmlMode" [hidden]="isButtonHidden('undo')" in Undo button and [disabled]="htmlMode" [hidden]="isButtonHidden('redo')" in Redo button.
Would not this solve the hidden issue for Undo and Redo buttons?

**Comment by kolkov** [comment]
Hi! It's a browser API limitation. If we want to use undo and redo functionality in this cases, we need fully rewrite browser implementation of this functions.

**Comment by RaquelJusticia** [comment]
Hi! I see, but are we talking about the same thing?
I am not talking about the functionality but the hidden possibility.
Thanks!

**Comment by kolkov** [comment]
@RaquelJusticia ok! Open a separate issue please.
