### ISSUE TITLE
Inconsistent HTML and defaultParagraphSeparator not working

### ISSUE THREAD

**Issue by ChrisBates** [kolkov/angular-editor#166]
I'm having an issue with the inconsistency of the HTML generated by the editor, and that the `defaultParagraphSeparator` option isn't working consistently (sometimes at all). I am not sure if I've setup something incorrectly, or this is a bug(s)?

**Setup**
```
editorConfig: AngularEditorConfig = {
  defaultParagraphSeparator: 'p',
  editable: true,
};
```

```
<angular-editor id="descriptionEditor" formControlName="description" [config]="editorConfig"></angular-editor>
```

**Behavior**
First up, most of the time the `defaultParagraphSeparator` is not wrapping paragraphs at all.
![image](https://user-images.githubusercontent.com/50668839/68430392-ea744c80-01ff-11ea-9a3c-8bf8580827c7.png)
![image](https://user-images.githubusercontent.com/50668839/68430418-f233f100-01ff-11ea-940d-4c78862bb9c0.png)

Secondly, the editor is randomly generating this:
![image](https://user-images.githubusercontent.com/50668839/68430564-33c49c00-0200-11ea-9f81-4c5cd8774e65.png)

**Comment by kolkov** [comment]
Hi! I think it's not editor issues, it's browser issues.
What browser you are using?

**Comment by kolkov** [comment]
![image](https://user-images.githubusercontent.com/3740898/68477716-2f6ba380-023f-11ea-8bd6-3097e678d0f5.png)

**Comment by ChrisBates** [comment]
@kolkov It looks like you've selected Paragraph instead of Standard, which does indeed use P tags then. But I have this hidden in my implementation, how can I make it use Paragraph by default?

**Comment by kolkov** [comment]
https://stackblitz.com/edit/angular-editor-wysiwyg try this demo please.

**Comment by ChrisBates** [comment]
I see, so the defaultParagraphSeparator selects the format... I took it to mean it changed the HTML tag used to separate paragraphs? Perhaps it could be clearer in the documentation.

Anyways, it works with fresh content. Any existing content is stuck in 'Standard', so I've enabled the selector box for the users to change old content.

Thanks @kolkov

**Comment by paddotk** [comment]
defaultParagraphSeparator stil doesn't seem to work. Whatever I configure this option with, the text always uses `<p>` tags for separation and in the editor the text type setting always springs back to 'Paragraph' when I press enter. This means I cannot insert line breaks unless I edit the html directly.

**Comment by Agatta** [comment]
Looks like this problem still exist -  when you switch between HTML code view in editor defaultParagraphSeparator  is not respected anymore and switches to <div>.

Fresh one: 

![image](https://github.com/user-attachments/assets/afdc8834-da55-447a-bda4-b53e53eef30b)


After switch to HTML code view, removing content and reentering

![image](https://github.com/user-attachments/assets/e0a51251-593d-46e3-81c1-98b18a64881f)
