### ISSUE TITLE
Change initial default block

### ISSUE THREAD

**Issue by viandanteoscuro** [kolkov/angular-editor#167]
Hi,

the first line of text has no tag, but i need that is encapsulated in p tag.
Is it possible?

Thanks
Massimo

**Comment by kolkov** [comment]
Hi! By default it's a simple text node. It turn to a block after click on Enter key. Use default separator in config. See example on stackblitz.

**Comment by viandanteoscuro** [comment]
It's the same with defaultSeparator... after enter key it change to Paragraph, but the initial text is always without tags.

**Comment by kolkov** [comment]
Yes. It's browser default behaviour.

**Comment by viandanteoscuro** [comment]
Ok, and do you know if it's possible to change it?
I'm using Chrome.

**Comment by kolkov** [comment]
We simple using contenteditable element in browser, no any magic. Try to fork this project and use it as you want.

**Comment by kolkov** [comment]
Or you may try to init editor with `p` block.

**Comment by grantmk** [comment]
Just a note I've forked this repo and made paragraph the standard initial format, as well as removing the non Heading formats. Find it here:

https://github.com/grantmk/angular-editor
and build at:
https://www.npmjs.com/package/@grantmk/angular-editor

Thanks for the initial hard work Kolkov!

**Comment by langthiennhai** [comment]
```
.code-block {
  background: #f4f4f4;
  padding: 10px;
  border-radius: 5px;
  font-family: monospace;
  white-space: pre-wrap;
  overflow-x: auto;
}
```
