### ISSUE TITLE
Wrong code returned by editor when in code edit mode

### ISSUE THREAD

**Issue by Albitos** [kolkov/angular-editor#172]
Steps to reproduce:

1. Insert some formatted content using WYSIWYG.
2. Value returned by model is "<b>asdasdasd</b> "
3. Switch to raw HTML editor.
4. Add any text.
5. Value returned by model is "&lt;b&gt;asdasdasd&lt;/b&gt;any".
6. Value should be: "<b>asdasdasd</b>any"

This basically means that when editing raw HTML we see text with encoded HTML entities instead of formatted value.

**Comment by Albitos** [comment]
Huh, that was fast. Thanks :)

**Comment by kolkov** [comment]
Yes, it was a very simple fix.  Thanks for contributing!
Other PRs are welcome.
