### ISSUE TITLE
Can not display the component

### ISSUE THREAD

**Issue by FARHANE** [kolkov/angular-editor#175]
Hello,
I get this error

`ERROR Error: Uncaught (in promise): TypeError: Object(...) is not a function
TypeError: Object(...) is not a function
    at kolkov-angular-editor.js:519
    at Module.../../node_modules/@kolkov/angular-editor/fesm5/kolkov-angular-editor.js (kolkov-angular-editor.js:521)
    at __webpack_require__ (bootstrap:83)`

**Comment by kolkov** [comment]
Hi! What browser and packajes versions you are using?

**Comment by iKONBobby** [comment]
hello,
I get this error too;
I using angular 7.0  and angular-editor 1.0.2 @kolkov

**Comment by kolkov** [comment]
@iKONBobby  For Angular 7.0 we must use AngularEditor 0.18.4+ instead 1.0.2

**Comment by iKONBobby** [comment]
Hello gus, I have another question is that I use angular material in my program. In i, .icomoon-liga, .material-icons, his font-family uses! Important which prevents the icon of the angular editor from being displayed. How can i solve this @kolkov

**Comment by iKONBobby** [comment]
Hello, I have another question is that I use angular material in my program. In i, .icomoon-liga, .material-icons, his font-family uses! Important which prevents the icon of the angular editor from being displayed. How can i solve this @kolkov

**Comment by iKONBobby** [comment]
When I manually added! Important to the font-family attribute of .fa [_ngcontent-c31] in the debug page of Google Chrome, it worked

**Comment by kolkov** [comment]
Haah, this is very strange. I use this editor in my own project with material library and all worked correctly. Provide an repo please with your config.
Thanks!

**Comment by iKONBobby** [comment]
this is my dependencies
"dependencies": {
    "@agm/core": "1.0.0-beta.5",
    "@angular/animations": "7.2.1",
    "@angular/cdk": "7.2.1",
    "@angular/common": "7.2.1",
    "@angular/compiler": "7.2.1",
    "@angular/core": "7.2.1",
    "@angular/flex-layout": "7.0.0-beta.23",
    "@angular/forms": "7.2.1",
    "@angular/http": "7.2.1",
    "@angular/material": "7.2.1",
    "@angular/material-moment-adapter": "7.2.1",
    "@angular/platform-browser": "7.2.1",
    "@angular/platform-browser-dynamic": "7.2.1",
    "@angular/pwa": "^0.800.3",
    "@angular/router": "7.2.1",
    "@angular/service-worker": "7.2.1",
    "@kolkov/angular-editor": "^0.18.7",
    "@ngrx/effects": "7.0.0",
    "@ngrx/router-store": "7.0.0",
    "@ngrx/store": "7.0.0",
    "@ngrx/store-devtools": "7.0.0",
    "@ngx-translate/core": "11.0.1",
    "@swimlane/dragula": "3.7.3",
    "@swimlane/ngx-charts": "10.0.0",
    "@swimlane/ngx-datatable": "14.0.0",
    "@swimlane/ngx-dnd": "6.0.0",
    "@types/prismjs": "1.9.0",
    "amazing-time-picker": "^1.8.0",
    "angular-calendar": "0.26.4",
    "angular-in-memory-web-api": "0.8.0",
    "angularx-qrcode": "^1.5.3",
    "bootstrap": "^4.3.1",
    "chart.js": "2.7.3",
    "classlist.js": "1.1.20150312",
    "core-js": "2.6.2",
    "d3": "5.7.0",
    "date-fns": "1.30.1",
    "e-ngx-print": "^5.3.1",
    "file-saver": "^2.0.0",
    "font-awesome": "^4.7.0",
    "hammerjs": "2.0.8",
    "lodash": "4.17.11",
    "moment": "2.23.0",
    "ng2-charts": "1.6.0",
    "ngrx-store-freeze": "0.2.4",
    "ngx-captcha": "^6.4.0",
    "ngx-color-picker": "7.3.0",
    "ngx-cookie-service": "2.1.0",
    "ngx-file-drop": "^8.0.8",
    "ngx-image-cropper": "^0.2.8",
    "ngx-input-file": "^1.0.4",
    "ngx-logger": "^4.0.3",
    "ngx-permissions": "^6.0.1",
    "perfect-scrollbar": "1.4.0",
    "prismjs": "1.15.0",
    "rxjs": "6.3.3",
    "saturn-datepicker": "6.0.1",
    "web-animations-js": "2.3.1",
    "xlsx": "^0.14.1",
    "zone.js": "0.8.28"
  },

and config 
config: AngularEditorConfig = {
    editable: true,
    spellcheck: true,
    height: 'auto',
    minHeight: '300px',
    width: 'auto',
    minWidth: '0',
    translate: 'yes',
    enableToolbar: true,
    showToolbar: true,
    placeholder: 'Enter text here...',
    defaultFontName: 'Arial',
    defaultFontSize: '2',
  };
and the Picture displayed incorrectly
![881576833556_ pic](https://user-images.githubusercontent.com/42308674/71244200-f39f2000-234c-11ea-92fa-3d68319a429b.jpg)

thanks every much!

**Comment by iKONBobby** [comment]
the css of material and editor
![891576834089_ pic](https://user-images.githubusercontent.com/42308674/71245156-17fbfc00-234f-11ea-90de-9e8c5287deb3.jpg)
![901576834253_ pic](https://user-images.githubusercontent.com/42308674/71245165-1c281980-234f-11ea-80d0-d1c6c50632c1.jpg)

**Comment by kolkov** [comment]
Provide your clonable repo with this bug on github.com please.

**Comment by kolkov** [comment]
Although the best, as I think, is to use our own SVG font in the Editor or SVG icons directly.

**Comment by iKONBobby** [comment]
I solved this problem. The original css file is not in the unchangeable file of material, but in the css of the changeable file in my project. I removed! Important. Then the problem was solved. Thank you！！

**Comment by kolkov** [comment]
Good news.)

**Comment by DusanBozovic** [comment]
can you provide a more detailed explanation, because i also have this issue
![image](https://user-images.githubusercontent.com/34100316/74917959-6d00d080-53d9-11ea-90ae-8e377e0fba07.png)

**Comment by carlospcpro** [comment]
@kolkov same oiginal error "core.js:1673 ERROR Error: Uncaught (in promise): TypeError: Object(...) is not a function
TypeError: Object(...) is not a function
    at kolkov-angular-editor.js:519
    at Object../node_modules/@kolkov/angular-editor/fesm5/kolkov-angular-editor.js (kolkov-angular-editor.js:521)"

Using
Angular CLI: 6.0.8
Node: 12.16.1     
OS: win32 x64     
Angular: 6.1.10  

And 
"@kolkov/angular-editor": "^1.1.2",
