### ISSUE TITLE
Background Color doesn't work

### ISSUE THREAD

**Issue by JCMilito** [kolkov/angular-editor#192]
So, only foreground color works.

Although the background color is applied in the editor, it does not appear in the resulting html.

What could be wrong?

**Comment by tscnn** [comment]
Same here, you can reproduce it in the official demo.

**Comment by AlkenArt** [comment]
I'm too facing the same Issue...
Hi, @kolkov Is there any update or any solution for this.

It will be so helpful if you reply to this.
Thanks in advance !!

**Comment by kolkov** [comment]
Hi! Do you have DOM sanitizer enabled?

**Comment by Kenji94** [comment]
Hi,
I have the same issue and the sanitized is enabled by default

**Comment by PeacefulCosmos** [comment]
same problem here, I had set the sanitize to true

**Comment by championboylay** [comment]
same issue. sanitize false doesn't work for me

**Comment by Abhiess5510** [comment]
> Hi! Do you have DOM sanitizer enabled?

What changes you made would you please elaborate ..i have tried sanitize true false both but not working for me in form.
