### ISSUE TITLE
angular 9

### ISSUE THREAD

**Issue by andrejm7** [kolkov/angular-editor#193]
hello .. if you update the angle to 9 there is an error

npm WARN @kolkov/angular-editor@1.0.2 requires a peer of @angular/common@>=8.0.0 <9 but none is installed. You must install peer dependencies 
yourself.
npm WARN @kolkov/angular-editor@1.0.2 requires a peer of @angular/core@>=8.0.0 <9 but none is installed. You must install peer dependencies yourself.
npm WARN @kolkov/angular-editor@1.0.2 requires a peer of @angular/forms@>=8.0.0 <9 but none is installed. You must install peer dependencies yourself.
npm WARN @kolkov/angular-editor@1.0.2 requires a peer of @angular/platform-browser@>=8.0.0 <9 but none is installed. You must install peer dependencies yourself.

**Comment by kolkov** [comment]
Hi! Try to use `--force `. I will try to test with latest  release soon as possible. Thanks!

**Comment by kolkov** [comment]
Try latest version please.

**Comment by andrejm7** [comment]
100% bro... thanks
