### ISSUE TITLE
Unable to hide Undo and Redo buttons

### ISSUE THREAD

**Issue by RaquelJusticia** [kolkov/angular-editor#194]
Hi Adrew Kolkov,

I am not able to hide Undo and Redo buttons so far.
What if adding [disabled]="htmlMode" [hidden]="isButtonHidden('undo')" in Undo button and [disabled]="htmlMode" [hidden]="isButtonHidden('redo')" in Redo button. (in file angular-editor-toolbar.component.html)
Would that be solve my issue?

Many thanks! :)

**Comment by kolkov** [comment]
Thanks! What version of package and Angular you are using?

**Comment by RaquelJusticia** [comment]
Hi! Angular 8 and package "@kolkov/angular-editor": "1.0.0"

**Comment by RaquelJusticia** [comment]
Just seen you made this change in version 1.1.0. I´m going to upgrade to this version, many thanks!

**Comment by RaquelJusticia** [comment]
The release is not published yet, but I will try later. I really appreciate your time. Thanks again.

**Comment by kolkov** [comment]
I can't see any publishing errors.
![SmartSelect_20200213-181248_Gmail](https://user-images.githubusercontent.com/3740898/74448765-8f9c6200-4e8c-11ea-8d01-a07dd9e9dc6d.jpg)

**Comment by RaquelJusticia** [comment]
I get this when trying to install version 1.1.0: (npm i @kolkov/angular-editor@1.1.0)

npm ERR! Unexpected end of input at 1:121011
npm ERR! -END PGP SIGNATURE-----\r\n"}},"0.15.6":{"name":"@kolkov/angular-edit
npm ERR!

**Comment by kolkov** [comment]
I tried to update at stackblitz, all works fine.

**Comment by RaquelJusticia** [comment]
Ok. I will try later today or tomorrow and let you know.
Thanks for your time.

**Comment by kolkov** [comment]
You can try to check npm caches.

**Comment by RaquelJusticia** [comment]
> You can try to check npm caches.

It worked and I am now able to hide those 2 buttons :)

**Comment by kolkov** [comment]
Thanks for the feedback!
