### ISSUE TITLE
Unable to pass withCredentials to the image upload URL

### ISSUE THREAD

**Issue by ale-rinaldi** [kolkov/angular-editor#199]
Currently, it's impossible to pass the "withCredentials" option to the HTTP POST call to upload an image. This makes uploading an image not working where there is a cross-origin API, with CORS correctly set, that requires cookie authentication to allow the upload.

**Comment by kolkov** [comment]
Hi! Thanks for this case.
Can you use request interceptors?

**Comment by ale-rinaldi** [comment]
I'm not sure I can inject the cookie with a request interceptor, but I will try for sure. I opened a pull request about this, if it can be useful.

Thanks!
