### ISSUE TITLE
insert img error

### ISSUE THREAD

**Issue by ddukda** [kolkov/angular-editor#20]
ERROR
Error: Cannot read property 'toLowerCase' of undefined

**Comment by kolkov** [comment]
What version of angular you are using?

**Comment by Ddakoshik** [comment]
in version 6 don't work, and I have the same problem
I try to use your editor and have some question how its work
Если есть время то отпиши на скайп roobot5 реально интересное решение но немного непонятно как воспользоватся загрузкой картинок

**Comment by kolkov** [comment]
This may help
https://github.com/kolkov/angular-editor/issues/5

**Comment by bandarumahesh** [comment]
i want image upload i saw the comments where can i place the code like below


{ "status":true, "originalName":"28279162_1980455641981763_1599997490751603080_n.jpg", "generatedName":"88f1aa6a-a9ce-4a3c-ada5-51cdf4bdaadd", "msg":"Image upload successful", "imageUrl":"data/img/product/88f1aa6a-a9ce-4a3c-ada5-51cdf4bdaadd.jpg" }

**Comment by kolkov** [comment]
@bandarumahesh Hi! Your backend must return json like this.
