### ISSUE TITLE
Error with tabIndex

### ISSUE THREAD

**Issue by chrgiga** [kolkov/angular-editor#212]
When I try to set tabIndex inside the angular-editor tag, the rendered HTML contains the word **tabIntex** instead of **tabIndex** (a **T** has been cast). This causes the editor to be inaccessible with the keyboard tab. Could you fix it please?
Thanks and great job!

**Comment by kolkov** [comment]
Thanks for reporting! Try new version please.

**Comment by chrgiga** [comment]
Thanks for your speed. Could you update the npm package too?

**Comment by kolkov** [comment]
![SmartSelect_20200326-081142_Gmail](https://user-images.githubusercontent.com/3740898/77612566-885f7e00-6f39-11ea-8cee-615ea7a5debb.jpg)
