### ISSUE TITLE
Cursor position is resetted to 0 after a paste

### ISSUE THREAD

**Issue by Kenji94** [kolkov/angular-editor#214]
Hi,

Is there a way to keep the original cursor position ?
After a paste, the cursor position is resetted to 0.
If you do multiple paste, it will add the new content to the top of the current texte.

Thanks

**Comment by shajirhaider** [comment]
Are you able to keep the original cursor position? If yes, please share the solution.

**Comment by Kenji94** [comment]
No I don't sorry but would like to
