### ISSUE TITLE
update for angular 10 - WARN

### ISSUE THREAD

**Issue by andrejm7** [kolkov/angular-editor#244]
npm WARN @kolkov/angular-editor@1.1.2 requires a peer of @angular/common@>=8.0.0 <10 but none is installed. You must install peer dependencies yourself.
npm WARN @kolkov/angular-editor@1.1.2 requires a peer of @angular/core@>=8.0.0 <10 but none is installed. You must install peer dependencies yourself.
npm WARN @kolkov/angular-editor@1.1.2 requires a peer of @angular/forms@>=8.0.0 <10 but none is installed. You must install peer dependencies yourself.
npm WARN @kolkov/angular-editor@1.1.2 requires a peer of @angular/platform-browser@>=8.0.0 <10 but none is installed. You must install peer dependencies yourself.

please.. you can update your lib?

**Comment by kolkov** [comment]
Thanks!
