### ISSUE TITLE
Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

### ISSUE THREAD

**Issue by mkubdev** [kolkov/angular-editor#268]
Seems this library is not compatible with Angular Ivy... 

Using :
Angular CLI: 9.1.0
Node: 13.10.1
OS: linux x64
Ivy Workspace: Yes

**Comment by kolkov** [comment]
@mkubdev no, this lib is Ivy compatible.

**Comment by mkubdev** [comment]
@kolkov ok, i'll deep a lil bit. Sry for this issue.
