### ISSUE TITLE
Can't set the height or the minheight of the editor

### ISSUE THREAD

**Issue by SidaouiBilel** [kolkov/angular-editor#28]
Hi 

Thank you for the awesome editor.

I tried following the tutorial and I set the height and minheight in the AngularEditorConfig Object but it doesn't work no matter what height I put it always stays small.

Cordially

**Comment by kolkov** [comment]
It's my real config that works as expected.
```
 editorConfig: AngularEditorConfig = {
    editable: true,
    spellcheck: true,
    height: '25rem',
    minHeight: '5rem',
    placeholder: 'Введите текст статьи...',
    translate: 'no',
    defaultFontName: 'Comic Sans MS',
    showToolbar: true,
    uploadUrl: 'v1/images',
    customClasses: [
      {
        name: "quote",
        class: "quote",
      },
      {
        name: 'redText',
        class: 'redText'
      },
      {
        name: "titleText",
        class: "titleText",
        tag: "h1",
      },
    ]
  };
```

**Comment by SidaouiBilel** [comment]
Ok It works now after I stopped the ng serve and restarted it. 

Other question, is it possible to set the max-height ?

**Comment by Idreeskema** [comment]
how can i set validtion in insert image?
