### ISSUE TITLE
HTML 4's “font” element should be replaced

### ISSUE THREAD

**Issue by EOussama** [kolkov/angular-editor#289]
As I've noticed, this package has some HTML 4 parts to it, noticeable especially on the output of colored or sized text.
The used `font` element doesn't play nice with the standards of the modern web as both the `color` and `size` attributes are deprecated in most use cases which makes this package obsolete when used with packages like [html-to-pdfmake](https://github.com/Aymkdn/html-to-pdfmake).

**Comment by Gaugeforever** [comment]
I have already added this as an issue here [Issue 264](https://github.com/kolkov/angular-editor/issues/264) Perhaps we can combine these.

**Comment by EOussama** [comment]
> I have already added this as an issue here [Issue 264](https://github.com/kolkov/angular-editor/issues/264) Perhaps we can combine these.

Totally, I made a PR on [html-to-pdfmake](https://github.com/Aymkdn/html-to-pdfmake)'s repository, they already merged the fix with their master branch, but it would also be cool if this package made its own workaround.

**Comment by kolkov** [comment]
Unfortunately this package uses native browser capabilities to generate html, and I'm not at all sure if this should be changed.

**Comment by EOussama** [comment]
Well then a workaround has already been implemented with html-to-pdfmake so this issue serves so purpose for now.
