### ISSUE TITLE
Color picker is badly positioned

### ISSUE THREAD

**Issue by eoussama** [kolkov/angular-editor#291]
As you can see in the following image, the color picker popup doesn't align with the trigger button:
![image](https://user-images.githubusercontent.com/22644543/95450469-3d014000-095e-11eb-9f32-1de9874e7b8f.png)

**Comment by EOussama** [comment]
I can't believe it's been almost two years.

**Comment by PhilLehmann** [comment]
Two years ✅

**Comment by EOussama** [comment]
> Two years ✅

Color me surprised.
Yes, pun intended.

**Comment by eoussama** [comment]
I guess it's safe to assume that OP has no bandwidth to ever look at this again.

**Comment by alexanderoliveira94** [comment]
> For anyone that needs this fix and don't want to wait indefinitely for package to get updated - you can add this SCSS to your global styles (styles.scss) file. I picked apart the PR that was mentioned in this issue to figure out how to get this work around in my own project
> 
> ```
> /* angular-editor color picker position fix */
> .angular-editor-toolbar {
>   input[type=color]:not(.color-picker) { /* added :not(.color-picker) so that this will be ignored when the package is updated */
>     display: initial !important;
>     position: absolute;
>     visibility: hidden;
>     border: none;
>     margin: 0;
>     padding: 0;  
>     height: 0;
>     width: 0;
>   }
> ```
> 
> ![image](https://user-images.githubusercontent.com/22281397/158426099-3ec23d92-8824-4013-9d6f-3e6b4a7972a7.png)

Essa sem dúvidas, ainda é a melhor solução pra esse problema, parabéns
