### ISSUE TITLE
Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by mayur-techcompose** [kolkov/angular-editor#3]
This error occur when I follow all step give by you I think some where object not found

**Comment by kolkov** [comment]
Hi! Provide some example at https://stackblitz.com/edit/angular-editor-wysiwyg please!

**Comment by kolkov** [comment]
If the issue is not solved, open it again.

**Comment by kolkov** [comment]
Hi! This version is for Angular 6+.

**Comment by HammeroT** [comment]
Updated to Angular 6, works fine now 👍 

Thanks for your Work!

**Comment by catalogo-de-posibilidades-exitosas** [comment]
Is there a version for angular 5?
