### ISSUE TITLE
Special Character converted into keycode

### ISSUE THREAD

**Issue by MinhPhuPham** [kolkov/angular-editor#309]
![image](https://user-images.githubusercontent.com/51711158/98458048-2fd6ab80-21bf-11eb-8af7-3d76e14a2d32.png)
i have text: "Chào các bạn" => htmlOutput is : ```<font face="Arial">Ch&#224;o c&#225;c b&#7841;n</font>```

**Comment by NESTicle** [comment]
There is any fix to that problem? Im facing the same issue. I dont know if has to be with sanitize: true?
