### ISSUE TITLE
Add Angular 11 support

### ISSUE THREAD

**Issue by jhormanrus** [kolkov/angular-editor#325]
### Please add support for Angular 11
```shell
npm ERR! Found: @angular/common@11.0.4
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~11.0.4" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@">=8.0.0 <11" from @kolkov/angular-editor@1.1.4
npm ERR! node_modules/@kolkov/angular-editor
npm ERR!   @kolkov/angular-editor@"*" from the root project
```

**Comment by justin-daniel** [comment]
Is there a road map for when Angular 11 will be supported?

**Comment by ayubUOL** [comment]
Does anyone know about how to install this package with Angular 11 ? 
Or some other Rich text editor !! Need Help

**Comment by ayubUOL** [comment]
I ran this command and it went successful for Angular v11.
`npm install @kolkov/angular-editor@1.0.0 --legacy-peer-deps`
