### ISSUE TITLE
Exposing (chane) event.

### ISSUE THREAD

**Issue by thruthesky** [kolkov/angular-editor#33]
Thank you for angular-editor.

Is there any better way than this to get update on change?
```
@ViewChild('editor') editr: AngularEditorComponent;
  ngAfterViewInit() {

    this.editr.registerOnChange((html) => {
      console.log('on change : ', html);
    });
 }
```

I want to do,
```
<angular-editor [(ngModel)]="htmlContent" (change)="onChange($event)"></angular-editor>
```
I looked up the code and it does not emit any event on change.

Can you do something like this?

```
@Output() change = new EventEmitter();

  onContentChange(html: string): void {

    if (typeof this.onChange === 'function') {
      this.change.emit( html );
      ....
 }
```

**Comment by kolkov** [comment]
Hi! `registerOnChange` is for `ControlValueAccessor` interface.
https://angular.io/api/forms/ControlValueAccessor
I'll see what better to think of by your request.

**Comment by kolkov** [comment]
@thruthesky why you don't like using `(ngModelChange)="onChange($event)"` event?

**Comment by thruthesky** [comment]
Ah... my bad.
Thank you ^^
