### ISSUE TITLE
Html code not working when editing

### ISSUE THREAD

**Issue by shakthifuture** [kolkov/angular-editor#336]
When loading the page with default Html code the **editor UI** work as expected and **output html** code also good, if any action perform in the editor, UI looks good but **output html code has removed all the css changes.**

I have created stackblitz here for better understanding https://stackblitz.com/edit/angular-editor-wysiwyg-i

Anything I am doing wrong?

**Comment by alexandr-efimov** [comment]
Same behaviour.

**Comment by BlackRoadCode** [comment]
I make a test and i dont lose any change, i did this:

1. copy the htmlContent in ts file (pre-charged content), 
2. edit. the content, in the HTML looks like i lose format. 
3. copy the new htmlContent (the html in the last step) and put into htmlContent (ts file)
4. the format is correct, i dont lose format.

**Comment by paddotk** [comment]
I suspect this has something to do with encoding (Cyrillic not being recognised correctly)?

**Comment by maruf571** [comment]
> Same behaviour. Example on typing any symbol (template form used): ![image](https://user-images.githubusercontent.com/13253360/105652443-eb0b0880-5ec1-11eb-97ae-87d82d737d91.png)

```
editorConfig: AngularEditorConfig = {
		sanitize: false,
	}
```
	
`<angular-editor [config]="editorConfig" [placeholder]="'Enter text here...'" [(ngModel)]="unicodeHtml"></angular-editor>`

**Comment by shakthifuture** [comment]
this solution worked for me.

https://stackoverflow.com/a/65641472/1862590
