### ISSUE TITLE
How to convert string to html ?

### ISSUE THREAD

**Issue by DruRio** [kolkov/angular-editor#34]
From editor, text is stored as string with html tags and as string is show. How to convert those tags to real html ?

**Comment by kolkov** [comment]
Hi! Please see this questions on Stack Owerflow:
https://stackoverflow.com/questions/3103962/converting-html-string-into-dom-elements
https://stackoverflow.com/questions/494143/creating-a-new-dom-element-from-an-html-string-using-built-in-dom-methods-or-pro
