### ISSUE TITLE
Blur - event

### ISSUE THREAD

**Issue by aalekseev96** [kolkov/angular-editor#36]
The blur-event in the editor doesn`t work correctly, it runs only for textarea field. What can be done to make blur works for all?

**Comment by kolkov** [comment]
Do you mean that the event is triggered when you click on the buttons of the editor?

**Comment by aalekseev96** [comment]
Yes.

**Comment by aalekseev96** [comment]
How can we fix it?

**Comment by kolkov** [comment]
I think we can check every click on a button and fire this event only when no button is pressed.

**Comment by pteyssedre** [comment]
Hi,

Thanks for the fix, but for me the blur is still not working. I have version 0.13.1 and yet the blur doesn't work. I also try with the online code demo and no luck there. The focus works perfectly but not the blur.

Any change to have a fix for that ?

**Comment by Alhamou** [comment]
the blur for me is not working, it is some fixed?
