### ISSUE TITLE
Does not work with IE 11

### ISSUE THREAD

**Issue by W-J-K** [kolkov/angular-editor#37]
I like the editor, but it seems completely broken with IE 11.   Is IE supported?

For example, just load the demo site in IE 11 https://angular-editor-wysiwyg.stackblitz.io/

**Comment by cristiansandru11** [comment]
Same thing.

**Comment by kolkov** [comment]
Hi! Try to use this polyfills for old IE:
![image](https://user-images.githubusercontent.com/3740898/48944320-42ef0300-ef37-11e8-88e3-9412145a66a7.png)

**Comment by skumar-mca** [comment]
Hi,

Image upload is not working in IE 11. Error received 'This function is not supported'.

Can anyone help please. Thanks in advance.

Also, does this plugin support adding some piece of HTML via code i.e., I can call a function with some HTML content and it gets added at cursor position?

**Comment by MichaelMcCoyTech** [comment]
Great project thanks.
But please can you sort this IE11 issue.  Try opening the Stackblitz demo in IE11 and look at the console errors....
"Error: This command is not supported."

I am getting same issue on my site and I have the polyfills uncommented.

**Comment by KevinLewisIowa** [comment]
This also doesn't work for me in IE. I can type in the editor and format it, but it is not binding to my model at all, the model does not change. I have the polyfills so that is not the issue.

**Comment by JtSangerman** [comment]
I am still getting "ERROR Error: This command is not supported." in the console any time I click into the editor although I have followed all the troubleshooting above. Are there any updates on this? IE11.

**Comment by kolkov** [comment]
Hi! This may help. This editor was bulded for evergreen browsers...
https://stackoverflow.com/questions/35140718/angular-2-4-5-not-working-in-ie11

**Comment by Seiifer** [comment]
Hi,

has anyone managed to fix this IE issue : "Error: This command is not supported." ?

The worst part is I can't even see which command is not supported, did anyone have the info so we can try to find a polyfill for it ?

I first thought it was the `fromCodePoint` String method but it doesnt look like it is.

**Comment by KevinLewisIowa** [comment]
I ended up using the PrimeNG editor module, it works in IE.

**Comment by xrobert35** [comment]
Hello :)

I have the same problem on  ie11. 

The error occure here  
https://github.com/kolkov/angular-editor/blob/dd3f2670a5cb76e02cc9b63352a9e9ce491c7281/projects/angular-editor/src/lib/angular-editor-toolbar.component.ts#L62

when the var "e"  have the value "link"

**Comment by xrobert35** [comment]
the real error is not here it came from the fact that  ie11 doesnt support  (input)  event on contenteditable="true" div. So the model is not up to date

**Comment by kolkov** [comment]
Closed as WAI.
