### ISSUE TITLE
How to re-upload exact same image again?

### ISSUE THREAD

**Issue by Sharanjaa** [kolkov/angular-editor#38]

**Comment by kolkov** [comment]
What do you mean by re-uploading the image? Using an already loaded image in the editor or uploading the exact same image?

**Comment by Sharanjaa** [comment]
Sorry for the inconvenience. 

When I upload an image and then delete it, I am unable to immediately upload the exact same image again as the next image.

Also, when I upload an image and then keep it without deleting, I am unable to immediately upload the same exact image as the very next image.

I am able to upload the same image twice only if I upload a different image in-between the two, but both at once is not possible.
