### ISSUE TITLE
When do we support the Angular 12 project?

### ISSUE THREAD

**Issue by IngoManthey** [kolkov/angular-editor#384]

**Comment by kolkov** [comment]
Hi! I think the current implementation should be building with Angular 12.
But I should try to switch to Ivy library distribution in next majore  version.

**Comment by IngoManthey** [comment]
Yes, I tested it, only when converting Angular 11 to 12 there was a problem because your project is only registered for a maximum of Angular 10. I deleted the project and entered it again after the conversion. When testing there was no problem.

**Comment by neelavar** [comment]
Cannot install the release `1.1.6` with Angular 12 - because:
```
 "peerDependencies": {
    "@angular/common": ">=8.0.0 <3",
    "@angular/core": ">=8.0.0 <13",
    "@angular/forms": ">=8.0.0 <13",
    "@angular/platform-browser": ">=8.0.0 <13",
    "rxjs": "^6.x.x"
 },
```

The `peerDependencies` has a typo for `@angular/common` dependency should be `<13`, instead of `<3`
