### ISSUE TITLE
Config option not working

### ISSUE THREAD

**Issue by udaykumar-8329** [kolkov/angular-editor#386]
Config option is not working

showing like below

Can't bind to 'config' since it isn't a known property of 'angular-editor'.
1. If 'angular-editor' is an Angular component and it has 'config' input, then verify that it is part of this module.
2. If 'angular-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

**Comment by udaykumar-8329** [comment]
Got it

**Comment by mitch85** [comment]
> Got it

how???
