### ISSUE TITLE
Setting ID attribute to editor

### ISSUE THREAD

**Issue by VladMstv** [kolkov/angular-editor#4]
Hello. I have two editors on same page. Is there an option to set ones id or something like that, cause pressing buttons on second editor causes focusing them in the first one.

**Comment by kolkov** [comment]
I think that no problem for this. I need to change some logic .

**Comment by santonini-ppa** [comment]
Hello. I also noticed the same thing. This problem does not allow me to use multiple editors on the same page because they make the page non-compliant with the accessibility constraints imposed in my country. Is it possible to release a fix to solve the problem? Thank you.

**Comment by kolkov** [comment]
What restrictions are accepted in your country?

**Comment by santonini-ppa** [comment]
There can be no duplicate identifiers (id) on the same html page.
Seeing the source code (angular-editor.component.html) I noticed that id = "editor" and id = "angularEditor" are wired inside the code.
It would be better to use only the angular id (#editor, #angularEditor).

**Comment by kolkov** [comment]
@santonini-ppa This code works fine for me at:
https://angular-editor.kolkov.ru/

```
<div class="container">
  <h1>Angular Editor</h1>
  <angular-editor id="editor1" [(ngModel)]="htmlContent1" [config]="config1" (ngModelChange)="onChange($event)" (blur)="onBlur($event)"></angular-editor>

  <!--<div *ngIf="htmlContent" class="htmlblock block">-->
  <h6>HTML Output</h6>
  <div class="html">
    {{ htmlContent1 }}
  </div>
  <!--</div>-->

  <angular-editor id="editor2" [(ngModel)]="htmlContent2" [config]="config2" (ngModelChange)="onChange($event)"></angular-editor>
</div>
```

**Comment by santonini-ppa** [comment]
I took a screenshot of html code generated on the page that you have shown me.
In the image I highlighted duplicate ids.
[https://drive.google.com/open?id=1i-YysslWg3OpRiBcqyXgm7TpOAjiokqH](url)

From W3C specifications id must be unique on the web page
[https://www.w3.org/TR/WCAG20-TECHS/H93.html](url)

**Comment by swapnali42** [comment]
**I want to add text cursor position in angular-editor textarea.** Please let me know how can I do that.
**Below is the html file code where I'm going to insert selected value from dropdown into angular-editor textarea.**
`<div class="col-4">`
`<select name="DynamicVariable" required (change)="selectChangeHandler($event)" id="f2" >`
`<option *ngFor="let productId of dynamicVaribleIDArray;">{{productId}}</option>`
` </select>`
`</div>`
`<angular-editor formControlName="des"  id="angularEditor" [config]="editorConfig">`
`<div class="angular-editor-wrapper">`
`<div class="angular-editor-textarea" id="angulareditorTextarea">`
`</div`
`</div>`
`</angular-editor`>

**Below is the .ts file code where I'm going to patch selected value from dropdown into angular-editor textarea.**
` this.selectedID = event.target.value;`
`this.productForm.controls.des.setValue(this.selectedID);`
