### ISSUE TITLE
Angular Ivy Distribution

### ISSUE THREAD

**Issue by chuma2150** [kolkov/angular-editor#427]
When installing packages with latest angular v13, a warning is popping up:
Processing legacy "View Engine" libraries:

@kolkov/angular-editor [es2015/esm2015] (https://github.com/kolkov/angular-editor)
Encourage the library authors to publish an Ivy distribution.
Thea reason for this is:
https://blog.angular.io/angular-v13-is-now-available-cce66f7bc296
Refer to point "State of View Engine"

**Comment by kolkov** [comment]
Thanks for the link!
First I tried to move my other libs to new format, but tests passed only local, not on Travis CI. 
https://github.com/kolkov/ngx-gallery/tree/angular13
I will try to discover this problem.

**Comment by kolkov** [comment]
Hi! Try new major release v2.0.0.

**Comment by Kashtan4ik** [comment]
> Hi! Try new major release v2.0.0.

It seems the package isn't compatible with Angular Ivy (Angular 13.2).

**Comment by chuma2150** [comment]
works. thanks.
forgot to close issue. done it now. much appreciated
