### ISSUE TITLE
Zoom in toolbar

### ISSUE THREAD

**Issue by TauanMatos** [kolkov/angular-editor#45]
How can I increase the size of the toolbar?

It is really small.
![image](https://user-images.githubusercontent.com/23512680/49225230-457fab80-f3c2-11e8-9b7f-cf01e8b54b5d.png)

**Comment by rodneykendall** [comment]
Add this CSS to your component:
.angular-editor-toolbar {
  transform: scale(1.5);
  transform-origin: 0 0;
}
Just change the scale to whatever size makes it look the best for you.

**Comment by TauanMatos** [comment]
Thanks.
