### ISSUE TITLE
Is there an option to paste without styles?

### ISSUE THREAD

**Issue by GiovaniCano** [kolkov/angular-editor#476]
When I paste, the styles from the source are included and weird things happen.

**Comment by devOneto** [comment]
Same problem. I've tried to access the clipboard data - when component starts - , clean it, and them paste it. But it's duplicating the text.

**Comment by devOneto** [comment]
Oh! i found this: #318 . Just adding rawPaste as true on configurations. And worked!

**Comment by GiovaniCano** [comment]
Yeah, that's the option, thanks :D
