### ISSUE TITLE
Bug with focus

### ISSUE THREAD

**Issue by ConstellationHoundDogs** [kolkov/angular-editor#49]
With 2 editors on one page, there is problem:
1. Focus first editor
2. Make changes (some text)
3. Click on any control of toolbar on the second editor

Bug: control of the second editors toolbar applies to the first (focused) editor

I found fix in the code:
In the AngularEditorComponent in function executeCommand move this.onEditorFocus(); call before anything else

**Comment by kolkov** [comment]
Hi! Thanks for this report.
