### ISSUE TITLE
Not able to implement validations like required.

### ISSUE THREAD

**Issue by skumar-mca** [kolkov/angular-editor#53]
Hi,

I wish to implement validation like required and get error details, if any error occurs. Similar to other angular error objects.

**Comment by kolkov** [comment]
Hi! Is there something not working there? It seems I was trying to make a standard implementation ...

**Comment by mebibou** [comment]
@kolkov I confirm this is not working. I have this form definition:
```
this.form = this.formBuilder.group({
  signature: [{
    value: undefined,
    disabled: false
  }, Validators.required]
});
```
Then when I submit the form and retrieve the value, even if the content is empty (and I see the placeholder so I assume it is), the value is `<br>` and the form control is therefore valid. Value should be empty or null and form control invalid

**Comment by mebibou** [comment]
FYI I created a small validator to fix this:
```typescript
class AngularEditorValidator {
  static required(): ValidatorFn {
    return (currentControl: AbstractControl): ValidationErrors|null => {
      if (currentControl.value === '<br>') {
        return {required: true};
      }
      return null;
    };
  }
}
```
and use it
```
Validators.compose([
  Validators.required,
  AngularEditorValidator.required()
 ]
```

**Comment by thamathar** [comment]
I know has been a long time, but would be possible to elaborate a little more on this "fix" ?! Since I needed to implement a validation for the editor

**Comment by kolkov** [comment]
Thanks! Can you make a PR please?

**Comment by thamathar** [comment]
PR ?! Sorry for not knowing the meaning of it.

**Comment by ils-nikhilp** [comment]
Hi, 
I am facing the same issue, Is there any update on this.

**Comment by anandjaisy** [comment]
The required validation works, but can we make the text editor border as red ?

**Comment by anandjaisy** [comment]
Is there any solution to make the border red on validation error ??
