### ISSUE TITLE
Placeholder Binding Issue 

### ISSUE THREAD

**Issue by Dainwright** [kolkov/angular-editor#59]
I tried the method listed in the readme:
`<angular-editor [placeholder]="'Enter text here...'" [(ngModel)]="htmlContent"></angular-editor>`
both on my local install and on the [stackblitz example](https://stackblitz.com/edit/angular-editor-wysiwyg) . Both receive an error related to binding to `placeholder`:

Stackblitz:

> Error in /turbo_modules/@angular/compiler@7.0.4/bundles/compiler.umd.js (2617:21)
> Template parse errors:
> Can't bind to 'placeholder' since it isn't a known property of 'angular-editor'.
> 1. If 'angular-editor' is an Angular component and it has 'placeholder' input, then verify that it is part of this module.
> 2. If 'angular-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
> 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
> <p>Native WYSIWYG editor for Angular 6+</p> 
> </header>
> <angular-editor [ERROR ->][placeholder]="'custom placeholder'" [(ngModel)]="htmlContent" [config]="config"></angular-editor>
> "): ng:///AppModule/AppComponent.html@5:20

Local:

> Uncaught Error: Template parse errors:
> Can't bind to 'placeholder' since it isn't a known property of 'angular-editor'.
> 1. If 'angular-editor' is an Angular component and it has 'placeholder' input, then verify that it is part of this module.
> 2. If 'angular-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
> 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
> <div class="container">
>   <form (ngSubmit)="onSubmit()" #memberForm="ngForm">
>     <angular-editor [ERROR ->][placeholder]="'Enter text here...'" [(ngModel)]="concert.notes"></angular-editor>
> ...

**This occurs using angular 7.1.0 locally and 7.0.4 on stackblitz**

**Comment by usuf13** [comment]
have the same issue in my app (Angular 6)
the problem not in  placeholder
by some reason 'angular-editor' unknown element :(

**Comment by usuf13** [comment]
adding FormsModule to my component module fixed the problem

**Comment by ohabash** [comment]
@usuf13 adding `import { FormsModule } from '@angular/forms';` to the component did not work.

@Miguel-Lara adding `config:{}` to the component ts and updating the markup as described did not work

**Comment by usuf13** [comment]
@ohabash are you added FormsModule to the module of component?

**Comment by mdeeb900** [comment]
I have multiple editors for "angular-editor" in my html,  so in this case I have to define for each  config variable in my .ts file to solve the placeholder issue, or there another solution?
Please help as all of them have same config property.

**Comment by kolkov** [comment]
This issue was fixed. Try new version please!

**Comment by vamsi58** [comment]
Can we make outline-color(on focus) configurable in this editor?

**Comment by kolkov** [comment]
@vamsi58 thanks! Create new issue please.
