### ISSUE TITLE
There is no color picker when clicking on Text color and Background color

### ISSUE THREAD

**Issue by lynx-r** [kolkov/angular-editor#6]
https://monosnap.com/file/tKxSfUmqOBbonGQEDBOwUPnAt8AwYz

The color picker doesn't open at all. I tried to switch the window in case if it was overlayed by the browser window.

**Comment by lynx-r** [comment]
Not fixed.

**Comment by kolkov** [comment]
Hi! I specially installed latest FF and test it, all fixed.
Try again without cache.

**Comment by lynx-r** [comment]
Sorry, I missed that it doesn't work in Safari.

**Comment by kolkov** [comment]
In mobile version of Safari on Android it's works as expected.

**Comment by kolkov** [comment]
![smartselectimage_2018-06-22-18-01-36](https://user-images.githubusercontent.com/3740898/41783820-860336d0-7646-11e8-8348-08503a84fd94.png)

**Comment by kolkov** [comment]
![smartselectimage_2018-06-22-18-03-43](https://user-images.githubusercontent.com/3740898/41783855-a2b539ea-7646-11e8-8033-753a7094ddb5.png)

**Comment by lynx-r** [comment]
https://monosnap.com/file/UtmV7IG7aocvigccU6NhV1Pcwy7BLn

**Comment by kolkov** [comment]
It seems to me that this is an old version of the application. On mobile versions, buttons and selects are equal in height.

**Comment by kolkov** [comment]
Unfortunately there is no Safari for Windows browser available. :(
Try to identify the problem yourself.

**Comment by Muffin8175** [comment]
I confirm that the both color pickers do not show in Safari, but width this [solution](https://github.com/kolkov/angular-editor/issues/291#issuecomment-1068197166) on the other thread, it is back:

    .angular-editor-toolbar input[type=color]:not(.color-picker) {
        display: initial !important;
        position: absolute;
        visibility: hidden;
        border: none;
        margin: 0;
        padding: 0;
        height: 0;
        width: 0;
    }
