### ISSUE TITLE
Insert HTML to cursor

### ISSUE THREAD

**Issue by sclausen** [kolkov/angular-editor#61]
I would like to insert custom html into the text, so it would be nice to not being forced to do something like `(<any>this._angularEditorService).insertHtml(html)`. Could you please make `insertHtml` public?

**Comment by rajee7009** [comment]
Hi, I've tried this code but it insert beginning of the text. How we find exact position of the cursor or Pointer.

this.editor.editorService.insertHtml(event)

**Comment by sclausen** [comment]
> How we find exact position of the cursor or Pointer.

If I‘m right, this editor uses the deprecated `document.execCommand` method which uses the current cursor position for inserting.
It seems the command `insertHtml` is not supported by IE though.

https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand

**Comment by rajee7009** [comment]
Thanks the update @sclausen. I've used **angular-mentions** for my issue. when I create email predefined template that time I need to insert predefined placeholders like **{name} {address}**. Now my issue resolved using  **angular-mentions**.
