### ISSUE TITLE
Bold and Italic not working

### ISSUE THREAD

**Issue by MatiasChao** [kolkov/angular-editor#63]
I updated Bootstrap to 4 and now bold text and Italic text are not working.

I'm using version:
"@kolkov/angular-editor": "^0.13.1",

Any ideas?

**Comment by AhmadShahid** [comment]
did you found any solution i am also facing the same issue?

**Comment by zijianhuang** [comment]
I think this had been fixed already in 0.13.1., and I am using "@ng-bootstrap/ng-bootstrap": "^4.0.0"
though I had never used releases before 0.13.1.

**Comment by kolkov** [comment]
Please reopen if needed
