### ISSUE TITLE
Add ability to set headers for image upload request (eg. for JWT token) or use standard HttpClient

### ISSUE THREAD

**Issue by tomchovanec** [kolkov/angular-editor#67]
Could you please add possibility to set HTTP request headers?
Or just use standard HttpClient class that already can have it's own interceptors (this could be the clean way).

Thank you for this great project

**Comment by qqaimh** [comment]
the same

**Comment by kolkov** [comment]
@tomchovanec what do you mean by standart http class?

**Comment by tomchovanec** [comment]
> @tomchovanec what do you mean by standart http class?

It seems that I'm wrong.... Angular already supports HttpInterceptors (that can be used for JWT tokens) and because you use standard HttpClient, it should work.  Maybe it wasn't working as I expected, so I have raised this issue. I'm sorry, but I cannot provide additional info, becase we have left this editor on out project.

**Comment by qqaimh** [comment]
> @tomchovanec what do you mean by standart http class?

The back server should response a url string or a json?

**Comment by kolkov** [comment]
@qqaimh read this issue please https://github.com/kolkov/angular-editor/issues/5
