### ISSUE TITLE
Multi browser support

### ISSUE THREAD

**Issue by arunjai1994** [kolkov/angular-editor#68]
does it work on ios and safari browser if yes, doesn't work on ios and safari browser?

**Comment by kolkov** [comment]
Hi! This workes on safari for windows and android. 
I havn't ios devices for tests. (
Whats wrong?

**Comment by tomchovanec** [comment]
I found, that color picker doesn't work on Edge (windows) and Safari (macOS)
Also you have to change color, if you want to apply it (same color, different text blocks selected )

**Comment by Vishnupriya26** [comment]
Hi 
The editor Reactive Form is not  fire/ trigger in IE

**Comment by Vishnupriya26** [comment]
Hi 
The editor Reactive Form is not  fire/ trigger in IE

**Comment by kolkov** [comment]
@aiboy

**Comment by kildareflare** [comment]
I've not been able to test this myself yet, but my client reports that this control does not work on iOS.

On iOS safari, Applying focus in the text editor does bring up the keyboard, but when you type nothing appears

On Mac Safari, nothing happens when you try click into the text editor

I'll try and get some more details.

**Comment by zijianhuang** [comment]
Angular2+ works best with HTML5 and ES6. For older browsers like IE and Edge, proper polyfill may rescue, so you may need to check if the polyfill files have enough dependencies to maximize the compatibility with those poor browsers.

This editor works well in iPad Safari, mime is iPad 2017. I remember that in old iPad like the "New iPad" (3rd gen) could be having problem with Angular if no proper polyfill is loaded.

I had just tested https://angular-editor-wysiwyg.stackblitz.io/ on iPad 2018, iPad mini 4 with iOS 11, and iPad 5th with iOS 11, Mac Mojave, and Mac ElCapitan (Safari 9.1) as well, all working fine.  However, on iPad 4 iOS 7, the demo site is not loaded, nevertheless, disney.com on such old iPad looks, many things got broken.

I think this is more of business cases of whether to support very old browsers and iOS/Mac releases. And the issue may be more of Angular polyfill things.

**Comment by kolkov** [comment]
Reopen if problem persists ...

**Comment by arunjai1994** [comment]
Hi, apologize for delay in response. As @kildareflare said demo works fine in ios. In my application for swipe event, we are using hammers JS because of that it is crushing and doesn't work on ios but works fine in android.

**Comment by kolkov** [comment]
I try on Safari for Android, all works correctly.

**Comment by arunjai1994** [comment]
Yes @kolkov it works. but if we are using hammers JS (Swipe event) and the angular editor is within the swipe event div. it crashes and doesn't work.
for example:
Below the code will not work on IOS.  
```
<div (swipeleft)="swipe(idx, $event.type)" (swiperight)="swipe(idx, $event.type)">
 <angular-editor [config]="editorConfig" maxlength="10" ></angular-editor>
</div>
```
Below the code will work on IOS. And  

 ```
<div> <angular-editor [config]="editorConfig" maxlength="10" ></angular-editor></div>
```

**Comment by kolkov** [comment]
Humm, very strange, create simple project to reproduce this issue please.
