### ISSUE TITLE
Add IDs to last 4 buttons

### ISSUE THREAD

**Issue by Gaugeforever** [kolkov/angular-editor#69]
We need IDs for the last 4 buttons so they can be safely targeted using CSS.  I tried to push this to the branch myself (new to github) but can't figure out how or it's just disabled.

These buttons are unlink, insert image, insert horizontal rule, and clear formatting, 

Thanks

**Comment by Gaugeforever** [comment]
`<button [id]="'unlink-'+id" type="button" class="angular-editor-button" (click)="triggerCommand('unlink')"
            title="Unlink" [disabled]="htmlMode" tabindex="-1">
      <i class="fa fa-chain-broken"></i>
    </button>
    <input
      style="display: none"
      accept="image/*"
      type="file" (change)="onFileChanged($event)"
      #fileInput>
    <button [id]="'insertImage-'+id" type="button" class="angular-editor-button" (click)="fileInput.click()" title="Insert Image"
            [disabled]="htmlMode" tabindex="-1"><i class="fa fa-image"></i></button>
    <button [id]="'insertHR-'+id" type="button" title="Horizontal Line" class="angular-editor-button"
            (click)="triggerCommand('insertHorizontalRule')" [disabled]="htmlMode" tabindex="-1"><i class="fa fa-minus"></i></button>
  </div>
  <div class="angular-editor-toolbar-set">
    <button [id]="'clearFormatting-'+id" type="button" title="Clear Formatting" class="angular-editor-button"
            (click)="triggerCommand('removeFormat')" [disabled]="htmlMode" tabindex="-1"><i class='fa fa-remove'></i></button>
  </div>`

**Comment by mebibou** [comment]
I think a better feature would be to be able to select which buttons to display, a bit like other more complex editors usually do. This would solve @Gaugeforever issue and will make configuration more flexible

**Comment by JoaoPortella** [comment]
+1

For now, this solved...

`button[title=Unlink], button[title='Insert Image'] {`
`   display: none;`
`}`
