### ISSUE TITLE
Width Specification

### ISSUE THREAD

**Issue by karthiak23** [kolkov/angular-editor#70]
I need to specify the width for this editor..how to do that??
and is there any options for adding maxwidth??

**Comment by rickithadi** [comment]
I have gotten around this by placing the <angular-editor> inside a card inside a div.

> <div class="col-md-12 ; mx-auto">
    <mat-card>
      <angular-editor
        [config]="editorConfig"
        [ngModel]="draft"
        (change)="onChange($event)"
      ></angular-editor>
      
      
      
      
    </mat-card>
  </div>

**Comment by Mayuri098** [comment]
Is there any way by which we can add this editor dynamically using jquery by just clicking on add button? I am working on angular10 project and there is a use case where I need to add and remove this editor dynamically using jquery.
