### ISSUE TITLE
Initialize control with HTML

### ISSUE THREAD

**Issue by elsawood** [kolkov/angular-editor#72]
Hi! Is it possible to initialize the angular-editor control with HTML and show the resulting text in the control (no HTML seen)? We provide a template to our users that they'll be able to modify. Then, we'll need to get the resulting HTML (to be used as the e-mail body message). Thanks!

**Comment by shubham-chandak** [comment]
> Hi! Is it possible to initialize the angular-editor control with HTML and show the resulting text in the control (no HTML seen)? We provide a template to our users that they'll be able to modify. Then, we'll need to get the resulting HTML (to be used as the e-mail body message). Thanks!
Please provide the html as a string to "ngModel" attribute as [(ngModel)]="<your html template>"
