### ISSUE TITLE
Disable link buttons when no selection

### ISSUE THREAD

**Issue by mebibou** [kolkov/angular-editor#74]
Currently, if no text is selected and the link button is clicked, it will add nothing at all making it look like it doesn't work. The buttons should be disabled when nothing is selected

**Comment by Srjkaa** [comment]
@kolkov Hello, Andrey!
If you will allow I can start work on it and provide a pull request in a few days.

**Comment by kolkov** [comment]
@Srjkaa Hi! PR always welcome)

**Comment by Srjkaa** [comment]
@kolkov Hi!
I had done with PR, it's opened and waiting for your agreement: https://github.com/kolkov/angular-editor/pull/108

**Comment by kolkov** [comment]
I close this with https://github.com/kolkov/angular-editor/pull/108
