### ISSUE TITLE
Cannot type in HTML mode

### ISSUE THREAD

**Issue by ChrisPanthera** [kolkov/angular-editor#81]
Hello,

When you go straight to the HTML editor and try typing you cannot type. You need to go to the text editor, type something in, then go back to the HTML editor and continue typing.

https://angular-editor-wysiwyg.stackblitz.io/

**Comment by enyosolutions** [comment]
Up !

**Comment by arnoldvakaria** [comment]
I have the same issue

**Comment by kolkov** [comment]
Hi! This is not an editor’s problem, as I see it ... I have to figure out how to get around this problem.

**Comment by arnoldvakaria** [comment]
Hello Andrey,
First of all thank you for your quick response! Many respects!If in preview mode I introduce some text and then  I try to edit in HTML mode it works fine till I delete all the content. So in case of HTML mode if the content empty can't edit it.

Regards,Arnold

|  |  |


 

    On Wednesday, June 12, 2019, 2:46:34 PM GMT+3, Andrey Kolkov <notifications@github.com> wrote:  
 
 
Hi! This is not an editor’s problem, as I see it ... I have to figure out how to get around this problem.

**Comment by kolkov** [comment]
Yes, the editable element remains in html, but if there is nothing in it, then it collapses. :(
We need to find some hack.

**Comment by tobias-g1** [comment]
Hi @kolkov,

This issue still seems to be present upon first use of the editor. 

1. Load page with the editor
2. Go straight to source code view
3. Unable to type HTML

[![Image from Gyazo](https://i.gyazo.com/f5ec95495a7bd4037f1037faca540795.gif)](https://gyazo.com/f5ec95495a7bd4037f1037faca540795)

Is this something you're able to replicate on your side? 

Thanks.

**Comment by kolkov** [comment]
@tobias-g1 I can't reproduce this. What version of editor you are using? 
https://angular-editor.kolkov.ru/

**Comment by sdelacasa77** [comment]
Hello, @tobias-g1 @kolkov 

I have the same problem right now.

Could you solve the bug?

When I press the button to see html code, it causes failure and does not let me do anything.

The bug is :

`kolkov-angular-editor.d.ts.AngularEditorComponent.html:3 ERROR TypeError: Cannot read property 'focus' of null
    at AngularEditorComponent.focus (kolkov-angular-editor.js:1210)
    at AngularEditorComponent.executeCommand (kolkov-angular-editor.js:1128)
    at Object.handleEvent (kolkov-angular-editor.d.ts.AngularEditorComponent.html:12)
    at handleEvent (core.js:43993)
    at callWithDebugContext (core.js:45632)
    at Object.debugHandleEvent [as handleEvent] (core.js:45247)
    at dispatchEvent (core.js:29804)
    at core.js:31837
    at SafeSubscriber.schedulerFn [as _next] (core.js:35379)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:183)`

package.json: 

` "dependencies": {
    "@angular/animations": "^8.2.14",
    "@angular/common": "^8.2.14",
    "@angular/compiler": "^8.2.14",
    "@angular/core": "^8.2.14",
    "@angular/forms": "^8.2.14",
    "@angular/platform-browser": "^8.2.14",
    "@angular/platform-browser-dynamic": "^8.2.14",
    "@angular/router": "^8.2.14",
    "@kolkov/angular-editor": "^1.1.1",
    "font-awesome": "^4.7.0",
    "rxjs": "~6.5.4",
    "tslib": "^1.11.0",
    "zone.js": "~0.9.1",
    "@agm/core": "1.0.0-beta.7",
    "@angular/cdk": "8.1.1",
    "@angular/flex-layout": "8.0.0-beta.26",
    "@angular/http": "7.2.1",
    "@angular/material": "8.1.1",
    "@angular/material-moment-adapter": "8.1.1",
    "@fortawesome/fontawesome-svg-core": "1.2.22",
    "@fortawesome/free-solid-svg-icons": "5.10.2",
    "@ngrx/effects": "8.1.0",
    "@ngrx/router-store": "8.1.0",
    "@ngrx/store": "8.1.0",
    "@ngrx/store-devtools": "8.1.0",
    "@ngx-translate/core": "11.0.1",
    "@swimlane/dragula": "3.8.0",
    "@swimlane/ngx-charts": "12.0.1",
    "@swimlane/ngx-datatable": "15.0.2",
    "@swimlane/ngx-dnd": "8.0.0",
    "@types/prismjs": "1.16.0",
    "angular-calendar": "0.27.13",
    "angular-in-memory-web-api": "0.8.0",
    "chart.js": "2.8.0",
    "classlist.js": "1.1.20150312",
    "core-js": "2.6.2",
    "d3": "5.9.7",
    "date-fns": "1.30.1",
    "hammerjs": "2.0.8",
    "html2canvas": "1.0.0-rc.5",
    "jspdf": "1.5.3",
    "lodash": "4.17.15",
    "moment": "2.24.0",
    "ng2-charts": "2.3.0",
    "ng2-file-upload": "1.3.0",
    "ngrx-store-freeze": "0.2.4",
    "ngx-color-picker": "8.1.0",
    "ngx-cookie-service": "2.2.0",
    "ngx-embed-video": "1.0.4",
    "ngx-spinner": "7.1.4",
    "node-sass": "4.12.0",
    "perfect-scrollbar": "1.4.0",
    "prismjs": "1.16.0",
    "rxjs-compat": "6.3.3",
    "web-animations-js": "2.3.2"
  },
  "devDependencies": {
    "@angularclass/hmr": "2.1.3",
    "@types/lodash": "4.14.136",
    "tslib": "1.10.0",
    "webpack-bundle-analyzer": "3.3.2",
    "@angular-devkit/build-angular": "~0.803.25",
    "@angular-devkit/build-ng-packagr": "~0.803.25",
    "@angular/cli": "^8.3.25",
    "@angular/compiler-cli": "^8.2.14",
    "@angular/language-service": "^8.2.14",
    "@types/jasmine": "~3.4.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~12.12.7",
    "codelyzer": "^5.1.0",
    "coveralls": "^3.0.4",
    "cpx": "^1.5.0",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "ng-packagr": "^5.7.1",
    "protractor": "~5.4.0",
    "ts-node": "~8.5.0",
    "tsickle": "~0.37.0",
    "tslint": "~5.20.1",
    "typescript": "~3.5.3"
  }`

Thanks.

**Comment by ck88ger** [comment]
Why this ticket is closed. Problem still existing?

**Comment by UNCareers** [comment]
Any solution?

**Comment by RobertHajbok** [comment]
I had the same issue, fixed it by setting editable to true on AngularEditorConfig

**Comment by sajeebchandan** [comment]
> I had the same issue, fixed it by setting editable to true on AngularEditorConfig

Finally this solution worked! That's why may be the ticket is closed.
