### ISSUE TITLE
Blur event should emit when there is no relatedTarget

### ISSUE THREAD

**Issue by aleksandar-kandzhichki** [kolkov/angular-editor#85]
I am currently using the (blur) event to trigger HTML Sanitization. 
It works awesome with the buttons of the editor, but when the user clicks on a background / between the buttons of the editor or any content that is not actual target, the event is not emitted even though the textarea gets focused out.

Could you please change 
https://github.com/kolkov/angular-editor/blob/307e329bb863d8504894162fc09237ed1c524b07/src/lib/angular-editor.component.ts#L127
to `if(!event.relatedTarget || (event.relatedTarget as HTMLElement).parentElement.className !== 'angular-editor-toolbar-set')`
So when you click on background outside of the editor, you would actually get the event emitted

**Comment by Srjkaa** [comment]
Hi, @aleksandar-kandzhichki !
If @kolkov will accept I can take a look on it and made PR with required changes which won't break any existing functionality.

**Comment by kolkov** [comment]
@Srjkaa thanks for PR.

**Comment by rastafan** [comment]
Hi,

i think the pull request merge on this issue did not go completely well. 
After the #109 pull (commit 0c756db), the code of the blur event is back to what it was before, meaning the `this.blur.emit('blur');` is still enclosed in the relatedTarget `if` block.

I tried to edit the code but could not test it in my project. the editor installed from npm works fine (except the blur event of course), while the git cloned and builded editor gives me error. Our project uses Angular 10. 

@kolkov can you please check? Thanks!

**Comment by pattersongarth** [comment]
Why is this still a bug 5 years later?
