### ISSUE TITLE
bug: inserting image on Android and iOS device not working

### ISSUE THREAD

**Issue by zijianhuang** [kolkov/angular-editor#86]
while inserting image is working well well on Windows.

on Android tablet, I used Chrome.
on iPad, I used Safari.

**Comment by kolkov** [comment]
Hi! On Android all work good. I haven't access to iPad or any iOS devices to debug it. On Safari for windows and Android all works!

**Comment by zijianhuang** [comment]
You are right, it is working on my Android phone. I had found it not working because I did not wait long enough since the HD photo takes long time to upload. I did find the other issues related which I will report in new issues.

**Comment by zijianhuang** [comment]
Also, by default, the ASP.NET Web API backend has a default maxRequestLength = 4MB, while my Samsung    A8 phone typically take a photo around 5.6MB, some high end phone may produce larger photo. The upload failed without proper feedback. 

So the uploading feature of the editor is working, as long as the backend accepts the upload.
