### ISSUE TITLE
How to get image from angular 6+ WYSIWYG editor image upload only frontend?

### ISSUE THREAD

**Issue by prakashksp20** [kolkov/angular-editor#88]
How to get image from angular 6+ WYSIWYG editor image upload only frontend?

_Originally posted by @prakashksp20 in https://github.com/kolkov/angular-editor/issues/5#issuecomment-489079407_

**Comment by mohyeid** [comment]
#80 I think this pull request may fix this issue

**Comment by kolkov** [comment]
Reopen if problem persists.
