### ISSUE TITLE
Toolbar Background Color

### ISSUE THREAD

**Issue by marct83** [kolkov/angular-editor#9]
We use a dark theme in our App. Is there a way to change the toolbar color?

**Comment by kolkov** [comment]
or use `::ng-deep`

**Comment by dannydoan43** [comment]
I am having trouble changing the toolbar color...I've tried these two in my post.component.css:
.angular-editor .angular-editor.toolbar::ng-deep {
    background-color:#2C2F33;
}
.angular-editor .angular-editor.toolbar{
    background-color:#2C2F33 !important;
}
how am I supposed to change the background color of the toolbar?

**Comment by gajen007** [comment]
Hi, I'm also using Dark Mode in my Ionic(Angular) App. I need to set the icon color (red) of the toolbar icons, as them appearing in white.
