### ISSUE TITLE
 "export 'ɵɵdefineInjectable' was not found in '@angular/core'

### ISSUE THREAD

**Issue by cpratiksha** [kolkov/angular-editor#90]
client?719c:147 [WDS] Warnings while compiling.
warnings @ client?719c:147
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:883
SockJS._transportMessage @ sockjs.js:881
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2957
wrapFn @ zone.js:1188
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:496
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
client?719c:153 ./node_modules/@kolkov/angular-editor/fesm5/kolkov-angular-editor.js
310:166-174 "export 'ɵɵinject' was not found in '@angular/core'
warnings @ client?719c:153
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:883
SockJS._transportMessage @ sockjs.js:881
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2957
wrapFn @ zone.js:1188
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:496
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
client?719c:153 ./node_modules/@kolkov/angular-editor/fesm5/kolkov-angular-editor.js
310:188-196 "export 'ɵɵinject' was not found in '@angular/core'
warnings @ client?719c:153
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:883
SockJS._transportMessage @ sockjs.js:881
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2957
wrapFn @ zone.js:1188
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:496
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
client?719c:153 ./node_modules/@kolkov/angular-editor/fesm5/kolkov-angular-editor.js
310:62-80 "export 'ɵɵdefineInjectable' was not found in '@angular/core'

**Comment by kolkov** [comment]
Thanks! Very strange, but I think that is result of building with Angular 8.0.0-rc.3. I will try to find problem.

**Comment by kolkov** [comment]
My main project builds successfully with this version:
![image](https://user-images.githubusercontent.com/3740898/57608672-11fe9b00-7576-11e9-9e71-a55aaeb8ceb4.png)
![image](https://user-images.githubusercontent.com/3740898/57608765-43776680-7576-11e9-87f2-9bde7021a2c0.png)
What version of `core-js` you are using? 
![image](https://user-images.githubusercontent.com/3740898/57608863-791c4f80-7576-11e9-8b19-c04e24d233a0.png)

**Comment by cpratiksha** [comment]
Thank you for quick response, I am checking with a version now.

**Comment by kennyrulez** [comment]
I can confirm this is a issue.
this is my package.json (omitting not related packages)
```
"@angular-devkit/build-angular": "0.13.9",
"@angular/cli": "7.3.9",
"@angular/common": "7.2.15",
"@angular/compiler": "7.2.15",
"@angular/compiler-cli": "7.2.15",
"@angular/core": "7.2.15",
"@angular/forms": "7.2.15",
"@angular/language-service": "7.2.15",
"@angular/platform-browser": "7.2.15",
"@angular/platform-browser-dynamic": "7.2.15",
"@angular/router": "7.2.15",
"@kolkov/angular-editor": "0.14.3",
"codelyzer": "5.0.1",
"core-js": "2.6.5",
"rxjs": "6.5.2",
"ts-node": "8.1.0",
"tslint": "5.16.0",
"typescript": "3.2.4",
"zone.js": "0.9.1"

```

**Comment by cpratiksha** [comment]
Facing the same problem,
My package.json file 
"private": true,
  "dependencies": {
    "@angular/animations": "^6.0.3",
    "@angular/cdk": "^6.4.0",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/material": "^6.4.0",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/pwa": "^0.6.8",
    "@angular/router": "^6.0.3",
    "@kolkov/angular-editor": "^0.14.3",
    "@ng-select/ng-select": "^2.13.1",
    "@ngx-utils/cookies": "^3.0.1",
    "@swimlane/ngx-datatable": "^13.0.1",
    "bootstrap": "^4.1.3",
    "core-js": "^2.5.4",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "jquery": "^3.3.1",
    "ng2-completer": "^2.0.8",
    "ngx-cookie-service": "^2.1.0",
    "ngx-popover": "0.0.16",
    "popper.js": "^1.14.3",
    "rxjs": "^6.0.0",
    "rxjs-compat": "^6.2.1",
    "zone.js": "^0.8.26"
  },
...................................................................................................................
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.1.1
node: 8.11.3
os: linux x64

**Comment by kolkov** [comment]
Thanks for the report. Try updated version please.

**Comment by cpratiksha** [comment]
Updated the version but still have the same issue
  
 / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.0.8
Node: 8.11.3
OS: linux x64
Angular: 6.0.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.4.0
@angular/cli                      6.0.8
@angular/material                 6.4.0
@angular/pwa                      0.6.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3

**Comment by kolkov** [comment]
https://stackblitz.com/edit/angular-editor-wysiwyg  - working example with Angular 6.0.5

**Comment by kolkov** [comment]
@cpratiksha Try to update your Angular to latest (or to latest 6.x.x) version by `ng update`. It's very simply.

**Comment by kolkov** [comment]
@cpratiksha Try this instructions https://update.angular.io/

**Comment by kennyrulez** [comment]
I can confirm that with 0.14.4 the app compiles so the issue is resolved for me

**Comment by kolkov** [comment]
@kennyrulez Thanks for the feedback!

**Comment by cpratiksha** [comment]
Thank you for your response .

**Comment by kolkov** [comment]
@cpratiksha Did you solve your problem?

**Comment by cpratiksha** [comment]
Yes I solved my problem with update my system version and used AngularEditorModule in app -module.ts file and shared module as well.
Thank you very much for your response
