### ISSUE TITLE
how to save data in plain text on front End .

### ISSUE THREAD

**Issue by cpratiksha** [kolkov/angular-editor#95]
I want to pass data to the backend in HTML format that is good, but how can I show the data in plain text on frontEnd.
data display on front end in such format 
`<div style="text-align: center;"><b style="background-color: transparent; -webkit-text-fill-color: black; font-size: 1rem;"><i>test data&nbsp;</i></b></div>

`

**Comment by cpratiksha** [comment]
(<any>this._angularEditorService).insertHtml(html)  In this way ? I don't want to add.
do we have any js code included for this or should I configure .
thank you .

**Comment by kolkov** [comment]
Hi! I think this may help, if you want display plain text from editor...
https://stackoverflow.com/questions/286813/how-do-you-convert-html-to-plain-text

**Comment by cpratiksha** [comment]
Thank you for your continued support.
