### ISSUE TITLE
How to apply any fonts?

### ISSUE THREAD

**Issue by nlakhtariyaks** [kolkov/angular-editor#97]
Hi @kolkov, You are doing a great job and I'm using your editor[this] library. Really happy to use it. But I've one question about how to add any external fonts into this library. 

For other fonts, I just add into `fonts: []` at `AngularEditorConfig` and it's working fine for below fonts: 
```
{ class: 'arial', name: 'Arial' },
{ class: 'calibri', name: 'Calibri' },
{ class: 'times-new-roman', name: 'Times New Roman' },
{ class: 'sans-serif', name: 'Sans Serif' }
```

But what about other fonts? This requirement is pure dynamic so I can't add which fonts will comes into this array. So, want to understand that how to append any fonts into this editor?

Thanks in advance.

**Comment by kolkov** [comment]
I suppose that these fonts are not in the system and they are not loaded from the outside ...

**Comment by kolkov** [comment]
Reopen please if problem persists.
